import { NextResponse } from "next/server";
import OpenAI from "openai";
import type { TableSchema } from "../../../lib/types";

export const runtime = "nodejs";

// ─── Generate SQL from schema definition ─────────────────────────────────────
function generateSQL(table: TableSchema): string {
  const cols = table.columns
    .map((c) => {
      const parts = [`  ${c.name} ${c.type}`];
      if (c.primary_key) parts.push("PRIMARY KEY DEFAULT uuid_generate_v4()");
      if (!c.nullable && !c.primary_key) parts.push("NOT NULL");
      if (c.unique && !c.primary_key) parts.push("UNIQUE");
      if (c.default) parts.push(`DEFAULT ${c.default}`);
      if (c.foreign_key) parts.push(`REFERENCES ${c.foreign_key.table}(${c.foreign_key.column}) ON DELETE CASCADE`);
      return parts.join(" ");
    })
    .join(",\n");

  const lines = [
    `CREATE TABLE IF NOT EXISTS ${table.name} (\n${cols}\n);`,
  ];

  // Indexes
  if (table.indexes) {
    for (const idx of table.indexes) {
      const unique = idx.unique ? "UNIQUE " : "";
      const type   = idx.type ? `USING ${idx.type} ` : "";
      lines.push(
        `CREATE ${unique}INDEX IF NOT EXISTS ${idx.name} ON ${table.name} ${type}(${idx.columns.join(", ")});`
      );
    }
  }

  // RLS
  if (table.rls_policies) {
    lines.push(`ALTER TABLE ${table.name} ENABLE ROW LEVEL SECURITY;`);
    for (const p of table.rls_policies) {
      const using     = p.using     ? ` USING (${p.using})`          : "";
      const withCheck = p.with_check ? ` WITH CHECK (${p.with_check})` : "";
      lines.push(
        `CREATE POLICY "${p.name}" ON ${table.name} FOR ${p.command}${using}${withCheck};`
      );
    }
  }

  // Triggers
  if (table.triggers) {
    for (const t of table.triggers) {
      lines.push(
        `CREATE TRIGGER ${t.name} ${t.timing} ${t.event} ON ${table.name} FOR EACH ROW EXECUTE FUNCTION ${t.function_name}();`
      );
    }
  }

  return lines.join("\n\n");
}

// ─── POST /api/database-builder ───────────────────────────────────────────────
export async function POST(req: Request) {
  try {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      return NextResponse.json({ error: "Missing OPENAI_API_KEY" }, { status: 500 });
    }

    const body = await req.json().catch(() => ({}));
    const description = typeof body.description === "string" ? body.description : "";
    const schema       = body.schema as TableSchema | undefined;

    // If schema is provided directly, just generate SQL
    if (schema && typeof schema === "object") {
      const sql = generateSQL(schema as TableSchema);
      return NextResponse.json({ ok: true, sql, schema });
    }

    if (!description) {
      return NextResponse.json({ error: "description or schema is required" }, { status: 400 });
    }

    const client = new OpenAI({ apiKey });
    const prompt = `You are a database architect for a Supabase (PostgreSQL) project.

Description: ${description}

Design a complete database schema. Return JSON matching this TypeScript type:
{
  "tables": [
    {
      "name": "string",
      "columns": [
        {
          "name": "string",
          "type": "UUID|TEXT|INTEGER|BOOLEAN|TIMESTAMPTZ|JSONB|NUMERIC|...",
          "nullable": boolean,
          "primary_key": boolean,
          "unique": boolean,
          "default": "string|null",
          "foreign_key": { "table": "string", "column": "string" } | null
        }
      ],
      "indexes": [{ "name": "string", "columns": ["..."], "unique": boolean }],
      "rls_policies": [{ "name": "string", "command": "ALL", "using": "true" }]
    }
  ]
}`;

    const response = await client.chat.completions.create({
      model: "gpt-4.1-mini",
      messages: [{ role: "user", content: prompt }],
      response_format: { type: "json_object" },
      max_tokens: 2048,
    });

    let tables: TableSchema[] = [];
    try {
      const parsed = JSON.parse(response.choices[0]?.message?.content ?? "{}");
      tables = Array.isArray(parsed.tables) ? parsed.tables : [];
    } catch {
      // ignore parse errors
    }

    const sqls = tables.map(generateSQL);
    const migration = [
      "-- Auto-generated by ZIVO AI Database Builder",
      `-- ${new Date().toISOString()}`,
      "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";",
      ...sqls,
    ].join("\n\n");

    return NextResponse.json({ ok: true, tables, migration });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Server error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
