/**
 * GET /api/projects/[id]/export.zip
 *
 * Returns all project_files for the given project as a downloadable ZIP archive.
 * Requires auth + ownership (RLS enforced via authed Supabase client).
 */
import { NextResponse } from 'next/server';
import JSZip from 'jszip';
import { extractBearerToken, getUserFromToken, createAuthedClient } from '@/lib/db/projects-db';

export const runtime = 'nodejs';

interface RouteParams {
  params: Promise<{ id: string }>;
}

export async function GET(req: Request, { params }: RouteParams) {
  const { id: projectId } = await params;

  const token = extractBearerToken(req.headers.get('Authorization'));
  if (!token) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const user = await getUserFromToken(token);
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const client = createAuthedClient(token);

  // Verify ownership
  const { data: project, error: projectError } = await client
    .from('projects')
    .select('id, title')
    .eq('id', projectId)
    .eq('owner_user_id', user.id)
    .single();

  if (projectError || !project) {
    return NextResponse.json({ error: 'Project not found' }, { status: 404 });
  }

  // Fetch all project files
  const { data: files, error: filesError } = await client
    .from('project_files')
    .select('path, content')
    .eq('project_id', projectId);

  if (filesError) {
    return NextResponse.json({ error: filesError.message }, { status: 500 });
  }

  const zip = new JSZip();

  for (const file of files ?? []) {
    zip.file(file.path, file.content);
  }

  // Add a minimal README if no files
  if ((files ?? []).length === 0) {
    zip.file(
      'README.md',
      `# ${(project as { title: string }).title}\n\nGenerated by [ZIVO-AI](https://zivo.ai).\n`
    );
  }

  const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });

  const safeTitle = ((project as { title: string }).title ?? 'project')
    .replace(/[^a-z0-9_-]/gi, '-')
    .toLowerCase();

  return new Response(new Uint8Array(zipBuffer), {
    status: 200,
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${safeTitle}.zip"`,
      'Content-Length': String(zipBuffer.length),
    },
  });
}
