// app/api/db-schema-generator/route.ts — Supabase-compatible database schema generator

import { NextResponse } from "next/server";
import OpenAI from "openai";

export const runtime = "nodejs";

export interface DbColumn {
  name: string;
  type: string;
  nullable: boolean;
}

export interface DbTable {
  name: string;
  columns: DbColumn[];
}

export interface DbSchemaFile {
  path: string;
  content: string;
  action: "create";
}

export interface DbSchemaResponse {
  files: DbSchemaFile[];
  sql: string;
  summary: string;
  tables: DbTable[];
}

const DB_SCHEMA_SYSTEM_PROMPT = `You are a database architect specializing in Supabase (PostgreSQL). Generate a complete database schema.

Given a list of table names and optional app name, return ONLY a valid JSON object (no markdown fences):
{
  "sql": "-- Full CREATE TABLE statements with proper PostgreSQL types\\nCREATE TABLE...",
  "summary": "Generated schema for X tables with relationships and RLS policies",
  "tables": [
    {
      "name": "users",
      "columns": [
        { "name": "id", "type": "uuid", "nullable": false },
        { "name": "email", "type": "text", "nullable": false },
        { "name": "created_at", "type": "timestamptz", "nullable": false }
      ]
    }
  ]
}

Rules:
- Always include id (uuid, DEFAULT gen_random_uuid()), created_at (timestamptz, DEFAULT now()), updated_at (timestamptz) columns
- Use proper PostgreSQL types: uuid, text, integer, boolean, timestamptz, jsonb, numeric
- Add PRIMARY KEY, UNIQUE, NOT NULL constraints where appropriate
- Add foreign key relationships based on table names (e.g. user_id references users)
- Include an ALTER TABLE ... ENABLE ROW LEVEL SECURITY; for each table
- Add basic RLS policies (select, insert, update for authenticated users)
- Return ONLY the JSON object`;

function getClient(): OpenAI {
  return new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
}

function buildSupabaseClient(appName: string): string {
  return `// lib/supabase-client.ts — Typed Supabase client helper for ${appName}
// Auto-generated by ZIVO AI

import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/lib/types/database";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);

export function getServerClient(serviceKey?: string) {
  return createClient<Database>(supabaseUrl, serviceKey ?? process.env.SUPABASE_SERVICE_ROLE_KEY!);
}
`;
}

interface AiSchemaResponse {
  sql?: string;
  summary?: string;
  tables?: DbTable[];
}

export async function POST(req: Request): Promise<Response> {
  if (!process.env.OPENAI_API_KEY) {
    return NextResponse.json({ error: "OPENAI_API_KEY is not configured" }, { status: 500 });
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { tables, appName } = body as { tables?: unknown; appName?: string };

  if (!Array.isArray(tables) || tables.length === 0) {
    return NextResponse.json({ error: "tables must be a non-empty array of strings" }, { status: 400 });
  }

  for (const t of tables) {
    if (typeof t !== "string") {
      return NextResponse.json({ error: "Each table must be a string" }, { status: 400 });
    }
  }

  const tableNames = tables as string[];
  const effectiveAppName = typeof appName === "string" && appName.trim() ? appName.trim() : "My App";

  try {
    const client = getClient();
    const response = await client.chat.completions.create({
      model: "gpt-4o",
      temperature: 0.2,
      max_tokens: 4096,
      messages: [
        { role: "system", content: DB_SCHEMA_SYSTEM_PROMPT },
        {
          role: "user",
          content: `Generate a Supabase PostgreSQL schema for the app "${effectiveAppName}" with these tables: ${tableNames.join(", ")}`,
        },
      ],
    });

    const rawText = response.choices?.[0]?.message?.content ?? "";
    let aiData: AiSchemaResponse = {};
    try {
      const jsonMatch = rawText.match(/\{[\s\S]*\}/);
      aiData = JSON.parse(jsonMatch ? jsonMatch[0] : rawText) as AiSchemaResponse;
    } catch {
      return NextResponse.json({ error: "Failed to parse AI response" }, { status: 500 });
    }

    const sql = aiData.sql ?? `-- Schema for ${effectiveAppName}\n-- Tables: ${tableNames.join(", ")}`;
    const schemaTablesData = aiData.tables ?? tableNames.map((name) => ({
      name,
      columns: [
        { name: "id", type: "uuid", nullable: false },
        { name: "created_at", type: "timestamptz", nullable: false },
        { name: "updated_at", type: "timestamptz", nullable: true },
      ],
    }));

    // Build TypeScript types from schema
    const tsTypes = buildTypeScriptTypes(schemaTablesData, effectiveAppName);

    const files: DbSchemaFile[] = [
      {
        path: "supabase/migrations/001_init.sql",
        content: sql,
        action: "create",
      },
      {
        path: "lib/types/database.ts",
        content: tsTypes,
        action: "create",
      },
      {
        path: "lib/supabase-client.ts",
        content: buildSupabaseClient(effectiveAppName),
        action: "create",
      },
    ];

    const result: DbSchemaResponse = {
      files,
      sql,
      summary: aiData.summary ?? `Generated schema for ${schemaTablesData.length} table(s): ${tableNames.join(", ")}`,
      tables: schemaTablesData,
    };

    return NextResponse.json(result);
  } catch (err: unknown) {
    return NextResponse.json(
      { error: (err as Error)?.message ?? "Failed to generate database schema" },
      { status: 500 }
    );
  }
}

function buildTypeScriptTypes(tables: DbTable[], appName: string): string {
  const typeMap: Record<string, string> = {
    uuid: "string",
    text: "string",
    varchar: "string",
    integer: "number",
    bigint: "number",
    numeric: "number",
    boolean: "boolean",
    timestamptz: "string",
    timestamp: "string",
    date: "string",
    jsonb: "Record<string, unknown>",
    json: "Record<string, unknown>",
  };

  const tableTypes = tables.map((table) => {
    const typeName = table.name
      .replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
      .replace(/^[a-z]/, (c) => c.toUpperCase());

    const columns = table.columns
      .map((col) => {
        const tsType = typeMap[col.type] ?? "unknown";
        return `    ${col.name}${col.nullable ? "?" : ""}: ${tsType};`;
      })
      .join("\n");

    return `  ${typeName}: {\n    Row: {\n${columns}\n    };\n    Insert: Partial<{\n${columns}\n    }>;\n    Update: Partial<{\n${columns}\n    }>;\n  };`;
  });

  return `// lib/types/database.ts — TypeScript types derived from Supabase schema
// Auto-generated by ZIVO AI for ${appName}

export type Database = {
  public: {
    Tables: {
${tableTypes.join("\n")}
    };
  };
};

${tables
  .map((table) => {
    const typeName = table.name
      .replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
      .replace(/^[a-z]/, (c) => c.toUpperCase());
    return `export type ${typeName} = Database["public"]["Tables"]["${table.name}"]["Row"];`;
  })
  .join("\n")}
`;
}
