/**
 * ZIVO-AI UI Component Library
 *
 * Barrel export for all reusable UI components.
 * Generated components span layout, data display, forms, feedback, navigation, and charts.
 */

// ─── Layout ─────────────────────────────────────────────────────────────────
export { TenantSwitcher } from "../TenantSwitcher";
export type { TenantSwitcherProps, Tenant, TenantRole } from "../TenantSwitcher";

// ─── Data Display ─────────────────────────────────────────────────────────────
// DataTable, StatsCard, KPIWidget, Timeline, ActivityFeed, Avatar, AvatarGroup
// are generated by the generate-ui-library API endpoint.

// ─── Feedback ────────────────────────────────────────────────────────────────
// Toast, Alert, ConfirmDialog, LoadingOverlay, ProgressBar, Skeleton
// are generated by the generate-ui-library API endpoint.

// ─── Navigation ──────────────────────────────────────────────────────────────
// Breadcrumbs, Tabs, Stepper, Pagination, CommandPalette (⌘K)
// are generated by the generate-ui-library API endpoint.

// ─── Charts ──────────────────────────────────────────────────────────────────
// LineChart, BarChart, PieChart, AreaChart, HeatMap (Recharts + D3)
// are generated by the generate-ui-library API endpoint.

// ─── Forms ───────────────────────────────────────────────────────────────────
// MultiSelect, DateRangePicker, ColorPicker, FileUpload, RichTextEditor,
// JSONEditor, CodeEditor (Monaco)
// are generated by the generate-ui-library API endpoint.

// ─── Media ───────────────────────────────────────────────────────────────────
// VideoPlayer, ImageGallery, AudioPlayer, MediaUploader
// are generated by the generate-media API endpoint.

// ─── Gamification ────────────────────────────────────────────────────────────
// AchievementToast, Leaderboard, UserLevel, BadgeGrid, StreakCounter
// are generated by the generate-gamification API endpoint.

// ─── Comments ────────────────────────────────────────────────────────────────
// CommentSystem, CommentThread, CommentComposer, ReactionPicker
// are generated by the generate-comments API endpoint.

// ─── Forms Builder ───────────────────────────────────────────────────────────
// FormBuilder, FieldPalette, FormCanvas, FieldSettings, FormPreview, SubmissionsTable
// are generated by the generate-form-builder API endpoint.

// ─── Export ──────────────────────────────────────────────────────────────────
// ExportButton
// is generated by the generate-export API endpoint.

// ─── Status ──────────────────────────────────────────────────────────────────
// StatusIndicator, UptimeGraph, IncidentTimeline
// are generated by the generate-status-page API endpoint.

// ─── Plugin System ───────────────────────────────────────────────────────────
// PluginCard, PluginManager
// are generated by the generate-plugin-system API endpoint.

// ─── SEO ─────────────────────────────────────────────────────────────────────
// JsonLd
// is generated by the generate-seo API endpoint.

// ─── Design Primitives ──────────────────────────────────────────────────────
export { Button, buttonVariants } from "./Button";
export type { ButtonProps, ButtonVariant, ButtonSize } from "./Button";

export { Card, CardHeader, CardTitle, CardContent, CardFooter } from "./Card";
export type { CardProps } from "./Card";

export { Input } from "./Input";
export type { InputProps } from "./Input";

export { Badge } from "./Badge";
export type { BadgeProps, BadgeVariant } from "./Badge";

export { Spinner } from "./Spinner";

export { Modal } from "./Modal";
export type { ModalProps } from "./Modal";

export { Tabs } from "./Tabs";
export type { TabsProps, TabItem } from "./Tabs";

export { Container } from "./Container";
export type { ContainerProps } from "./Container";

export { Stack } from "./Stack";
export type { StackProps } from "./Stack";

export { Grid, GridItem } from "./Grid";
export type { GridProps, GridItemProps } from "./Grid";
