// Enterprise Platform Definitions – 9 Vertical Platforms

export interface PlatformFeature {
  id: string;
  name: string;
  description: string;
}

export interface EnterprisePlatform {
  id: string;
  number: number;
  name: string;
  description: string;
  icon: string;
  color: string;
  features: string[];
}

export const ENTERPRISE_PLATFORMS: EnterprisePlatform[] = [
  {
    id: "healthcare",
    number: 71,
    name: "Advanced Healthcare Platform",
    description: "Hospital management system with patient records, EHR, telemedicine, and full clinical workflow.",
    icon: "🏥",
    color: "#0ea5e9",
    features: [
      "Hospital management system",
      "Patient registration",
      "Electronic health records (EHR)",
      "Doctor profiles & schedules",
      "Appointment booking",
      "Telemedicine integration",
      "Video consultation",
      "Prescription management",
      "Medical imaging storage",
      "Lab results tracking",
      "Billing & insurance",
      "Insurance verification",
      "Claim management",
      "Pharmacy integration",
      "Drug interaction checker",
      "Patient communication",
      "SMS notifications",
      "Email notifications",
      "Patient portal",
      "Health monitoring devices",
      "Wearable integration",
      "Emergency alerts",
      "Ambulance dispatch",
      "ICU management",
      "Ward management",
      "Bed allocation",
      "Staff scheduling",
      "Doctor on-call system",
      "Nurse assignment",
      "Medical equipment tracking",
      "Inventory management",
      "Supply chain",
      "HIPAA compliance",
      "Multi-hospital network",
    ],
  },
  {
    id: "university",
    number: 72,
    name: "University Platform",
    description: "Full campus management: course catalog, enrollment, grades, financial aid, housing, and alumni network.",
    icon: "🎓",
    color: "#8b5cf6",
    features: [
      "Student portal",
      "Course catalog",
      "Course enrollment",
      "Class schedules",
      "Room booking",
      "Attendance tracking",
      "Grade management",
      "Assignment tracking",
      "Exam scheduling",
      "Grade reporting",
      "Transcript generation",
      "GPA calculation",
      "Academic standing",
      "Dean's list",
      "Probation management",
      "Graduation planning",
      "Degree audit",
      "Prerequisites tracking",
      "Course recommendations",
      "Faculty profiles",
      "Faculty schedules",
      "Office hours",
      "Virtual classroom",
      "Video conferencing",
      "Discussion forums",
      "Assignment submission",
      "Plagiarism detection",
      "Peer review system",
      "Grading rubrics",
      "Feedback system",
      "Parent portal",
      "Alumni network",
      "Career services",
      "Job postings",
      "Resume building",
      "Interview scheduling",
      "Campus events",
      "Student clubs",
      "Event management",
      "Finance portal",
      "Tuition management",
      "Financial aid",
      "Scholarship tracking",
      "Payment plans",
      "Student housing",
      "Dorm management",
      "Roommate matching",
      "Campus security",
      "ID cards",
      "Library management",
      "Book checkout",
      "Research databases",
      "Parking management",
      "Bus schedules",
    ],
  },
  {
    id: "gym",
    number: 73,
    name: "Gym Management",
    description: "Complete gym & fitness studio: memberships, trainers, equipment, classes, and nutrition.",
    icon: "💪",
    color: "#f59e0b",
    features: [
      "Membership management",
      "Membership plans",
      "Recurring billing",
      "Payment processing",
      "Class scheduling",
      "Trainer profiles",
      "Trainer schedules",
      "Personal training",
      "Group fitness classes",
      "Class capacity",
      "Waitlist management",
      "Booking system",
      "Cancellation policy",
      "Attendance tracking",
      "Check-in system",
      "Equipment inventory",
      "Equipment maintenance",
      "Maintenance schedules",
      "Equipment status",
      "Repair tickets",
      "Locker management",
      "Locker assignment",
      "Access control",
      "RFID integration",
      "Member profiles",
      "Fitness goals",
      "Progress tracking",
      "Body metrics",
      "Workout history",
      "Performance analytics",
      "Member communication",
      "Push notifications",
      "Email campaigns",
      "SMS alerts",
      "Community feed",
      "Social features",
      "Member reviews",
      "Trainer ratings",
      "Class ratings",
      "Mobile app",
      "Wearable integration",
      "Virtual classes",
      "Streaming classes",
      "On-demand videos",
      "Nutrition plans",
      "Meal tracking",
      "Supplement store",
      "Retail integration",
      "Billing & invoicing",
      "Revenue reporting",
      "Staff management",
      "Staff scheduling",
      "Commission tracking",
    ],
  },
  {
    id: "restaurant",
    number: 74,
    name: "Restaurant Management",
    description: "Full-service restaurant: POS, kitchen display, inventory, delivery integrations, and loyalty.",
    icon: "🍽️",
    color: "#ef4444",
    features: [
      "POS system",
      "Order management",
      "Kitchen display system",
      "Table management",
      "Reservation system",
      "Menu management",
      "Pricing management",
      "Combo deals",
      "Special offers",
      "Ingredient tracking",
      "Recipe management",
      "Inventory management",
      "Stock alerts",
      "Supplier management",
      "Purchase orders",
      "Vendor management",
      "Cost tracking",
      "Food cost analysis",
      "Waste tracking",
      "Expiration date tracking",
      "Delivery partner integration",
      "DoorDash integration",
      "Uber Eats integration",
      "Online ordering",
      "Takeout management",
      "Catering orders",
      "Event management",
      "Staff management",
      "Staff scheduling",
      "Clock in/out",
      "Performance tracking",
      "Training programs",
      "Compliance tracking",
      "Food safety certification",
      "Health inspections",
      "Customer reviews",
      "Rating system",
      "Feedback collection",
      "Marketing campaigns",
      "Email marketing",
      "SMS marketing",
      "Loyalty program",
      "Rewards system",
      "Customer database",
      "Customer history",
      "Billing & invoicing",
      "Financial reporting",
      "Revenue analytics",
      "Labor cost analysis",
      "Profitability tracking",
      "Multi-location management",
      "Franchise support",
      "Supply chain optimization",
    ],
  },
  {
    id: "hotel",
    number: 75,
    name: "Hotel Management",
    description: "Property management system: rooms, housekeeping, concierge, events, and revenue management.",
    icon: "🏨",
    color: "#10b981",
    features: [
      "Room management",
      "Room types",
      "Room pricing",
      "Seasonal pricing",
      "Dynamic pricing",
      "Occupancy management",
      "Reservation system",
      "Booking engine",
      "Cancellation policy",
      "Guest profiles",
      "Guest history",
      "Loyalty program",
      "Rewards tracking",
      "Check-in system",
      "Digital check-in",
      "Mobile check-in",
      "Keyless entry",
      "Room access",
      "Housekeeping management",
      "Cleaning schedules",
      "Room status tracking",
      "Maintenance requests",
      "Maintenance tracking",
      "Preventive maintenance",
      "Work orders",
      "Staff assignment",
      "Staff scheduling",
      "Performance tracking",
      "Laundry management",
      "Linen tracking",
      "Inventory management",
      "Supply ordering",
      "Vendor management",
      "Guest communication",
      "SMS notifications",
      "Email notifications",
      "In-room messaging",
      "Concierge services",
      "Restaurant integration",
      "Room service",
      "Spa integration",
      "Wellness services",
      "Recreation activities",
      "Event management",
      "Meeting room booking",
      "Conference facilities",
      "AV equipment",
      "Catering services",
      "Parking management",
      "Valet services",
      "Transportation services",
      "Airport shuttle",
      "Billing & invoicing",
      "Revenue management",
      "Financial reporting",
      "Occupancy analytics",
    ],
  },
  {
    id: "airport",
    number: 76,
    name: "Airport Management",
    description: "Full airport operations: flight scheduling, baggage, crew, security, retail, and ground handling.",
    icon: "✈️",
    color: "#6366f1",
    features: [
      "Flight scheduling",
      "Gate management",
      "Flight status",
      "Delay management",
      "Cancellation management",
      "Crew management",
      "Crew scheduling",
      "Crew rest requirements",
      "Pilot assignment",
      "Flight attendant assignment",
      "Aircraft maintenance",
      "Maintenance scheduling",
      "Airworthiness tracking",
      "Passenger check-in",
      "Online check-in",
      "Mobile check-in",
      "Kiosk check-in",
      "Baggage management",
      "Baggage tracking",
      "Baggage tagging",
      "Baggage claim",
      "Lost baggage handling",
      "Baggage scanning",
      "Security integration",
      "TSA PreCheck",
      "Customs integration",
      "Immigration processing",
      "Gate assignment",
      "Boarding management",
      "Boarding passes",
      "Biometric scanning",
      "Lounge management",
      "Lounge access",
      "VIP services",
      "Concierge services",
      "Restaurant management",
      "Duty-free shops",
      "Retail management",
      "Parking management",
      "Transportation services",
      "Ground handling",
      "Catering services",
      "Fuel management",
      "De-icing services",
      "Runway management",
      "Air traffic control",
      "Weather integration",
      "Delay compensation",
      "Passenger communication",
      "SMS alerts",
      "Email alerts",
      "Mobile app",
    ],
  },
  {
    id: "car-dealership",
    number: 77,
    name: "Car Dealership",
    description: "Automotive retail: vehicle inventory, financing, trade-ins, service department, and CRM.",
    icon: "🚗",
    color: "#f97316",
    features: [
      "Vehicle inventory",
      "Vehicle specifications",
      "Pricing management",
      "Market pricing analysis",
      "Competitive pricing",
      "Inventory tracking",
      "Stock levels",
      "Vehicle status (new, used, certified)",
      "Mileage tracking",
      "Service history",
      "Accident history",
      "Title management",
      "Registration",
      "Inspection reports",
      "Vehicle photos",
      "360 view",
      "Virtual tours",
      "Test drive scheduling",
      "Test drive tracking",
      "Sales team management",
      "Sales tracking",
      "Commission tracking",
      "Deal management",
      "Financing options",
      "Loan management",
      "Interest rates",
      "Monthly payments",
      "Credit check",
      "Document management",
      "Trade-in valuation",
      "Trade-in processing",
      "Maintenance packages",
      "Extended warranties",
      "Insurance options",
      "Customer profiles",
      "Customer history",
      "Leads management",
      "Lead scoring",
      "CRM integration",
      "Email campaigns",
      "SMS campaigns",
      "Showroom management",
      "Appointment scheduling",
      "Customer communication",
      "Feedback collection",
      "Reviews & ratings",
      "Service department",
      "Service scheduling",
      "Vehicle servicing",
      "Parts management",
      "Warranty claims",
      "Recall management",
      "Financial reporting",
      "Inventory analytics",
    ],
  },
  {
    id: "fashion-ecommerce",
    number: 78,
    name: "Fashion E-Commerce",
    description: "Boutique & brand platform with AR virtual fitting room, styling, influencer tools, and subscriptions.",
    icon: "👗",
    color: "#ec4899",
    features: [
      "Product catalog",
      "Product images",
      "Product specifications",
      "Size charts",
      "Material information",
      "Care instructions",
      "Color variations",
      "Size availability",
      "Inventory management",
      "Stock tracking",
      "Stock alerts",
      "Supplier management",
      "Purchase orders",
      "Pricing management",
      "Dynamic pricing",
      "Discount management",
      "Flash sales",
      "Seasonal sales",
      "Collection management",
      "Designer profiles",
      "Brand management",
      "AR virtual fitting room",
      "AR try-on",
      "Body scanning",
      "Size recommendations",
      "Styling recommendations",
      "Personal shopper",
      "Style quiz",
      "Lookbook creation",
      "Outfit combinations",
      "Shopping cart",
      "Wishlist",
      "Product comparison",
      "Reviews & ratings",
      "Customer photos",
      "User-generated content",
      "Search functionality",
      "Filter options",
      "Browse by style",
      "Browse by occasion",
      "Browse by price",
      "Personalization engine",
      "Recommendation engine",
      "Customer segmentation",
      "Targeted marketing",
      "Email marketing",
      "SMS marketing",
      "Social media integration",
      "Instagram shopping",
      "TikTok shopping",
      "Influencer collaboration",
      "Order management",
      "Shipping integration",
      "Return management",
      "Exchange management",
      "Live chat support",
      "Video consultation",
      "Styling sessions",
      "Subscription boxes",
      "Rental service",
      "Loyalty program",
      "VIP customer tier",
    ],
  },
  {
    id: "entertainment-booking",
    number: 79,
    name: "Entertainment Booking",
    description: "Concert & event ticketing: venues, seating, dynamic pricing, live streaming, and merchandise.",
    icon: "🎟️",
    color: "#14b8a6",
    features: [
      "Event creation",
      "Event scheduling",
      "Venue management",
      "Venue capacity",
      "Seating management",
      "Seat selection",
      "Reserved seating",
      "General admission",
      "VIP packages",
      "Ticket types",
      "Ticket pricing",
      "Dynamic pricing",
      "Early bird pricing",
      "Group discounts",
      "Student discounts",
      "Senior discounts",
      "Family packages",
      "Artist/performer profiles",
      "Artist management",
      "Tour scheduling",
      "Multiple show dates",
      "Ticket sales",
      "Inventory management",
      "Ticket allocation",
      "Resale management",
      "Secondary market",
      "Ticketing API",
      "Mobile tickets",
      "Digital tickets",
      "Barcode scanning",
      "Entry management",
      "Guest list management",
      "Will-call management",
      "Payment processing",
      "Multiple payment methods",
      "Fraud prevention",
      "Refund management",
      "Cancellation policy",
      "Rescheduling",
      "Customer communication",
      "SMS notifications",
      "Email notifications",
      "Marketing campaigns",
      "Social media integration",
      "Fan engagement",
      "Pre-event content",
      "Live streaming",
      "Post-event content",
      "Photo gallery",
      "Video highlights",
      "Merchandise sales",
      "Parking management",
      "Transportation services",
      "Rating system",
      "Reviews & feedback",
    ],
  },
];

export const ENTERPRISE_AI_FEATURES = {
  aiMl: [
    "Predictive analytics",
    "Demand forecasting",
    "Inventory optimization",
    "Revenue optimization",
    "Dynamic pricing",
    "Customer lifetime value",
    "Churn prediction",
    "Anomaly detection",
    "Fraud detection",
    "Recommendation engines",
    "Computer vision",
    "Image recognition",
    "Document processing",
    "NLP sentiment analysis",
    "Chatbot AI",
    "Predictive maintenance",
    "Supply chain optimization",
    "Route optimization",
    "Workforce optimization",
  ],
  enterpriseManagement: [
    "Multi-company management",
    "Multi-location management",
    "Organizational hierarchy",
    "Department management",
    "Cost center management",
    "Profit center management",
    "Budget management",
    "Budget forecasting",
    "Expense tracking",
    "Approval workflows",
    "Purchase orders",
    "Requisition management",
    "Procurement management",
    "Vendor management",
    "Supplier management",
    "Contract management",
    "SLA management",
    "KPI tracking",
    "Balanced scorecard",
    "Strategic planning",
    "OKR management",
    "Goal tracking",
  ],
  advancedSecurity: [
    "Multi-factor authentication",
    "Single sign-on (SSO)",
    "OAuth integration",
    "API key management",
    "End-to-end encryption",
    "Data encryption",
    "Encryption at rest",
    "Encryption in transit",
    "Zero-knowledge architecture",
    "Threat detection",
    "Intrusion detection",
    "DDoS protection",
    "Rate limiting",
    "IP whitelisting",
    "Two-factor authentication",
    "Biometric authentication",
    "Compliance automation",
    "GDPR compliance",
    "CCPA compliance",
    "HIPAA compliance",
    "SOC 2 compliance",
    "ISO 27001 compliance",
    "PCI DSS compliance",
    "Data anonymization",
    "Privacy by design",
    "Security audit logs",
    "Activity monitoring",
  ],
  analyticsAndBi: [
    "Executive dashboards",
    "KPI dashboards",
    "Real-time dashboards",
    "Custom reports",
    "Scheduled reports",
    "Data warehousing",
    "ETL pipelines",
    "Data lake",
    "Big data processing",
    "Real-time analytics",
    "Historical analysis",
    "Predictive insights",
    "Prescriptive analytics",
    "Cohort analysis",
    "Funnel analysis",
    "Attribution modeling",
    "Customer journey mapping",
    "RFM analysis",
    "Segmentation analysis",
  ],
};

export const ENTERPRISE_INTEGRATIONS = {
  healthcare: [
    "Epic EHR", "Cerner", "AllScripts", "Athenahealth", "Medidata",
    "Veradigm", "DrFirst", "HL7", "FHIR", "NCBI",
    "PubMed", "Zocdoc", "Healthgrades", "CVS", "Walgreens",
  ],
  education: [
    "Salesforce", "Blackboard", "Canvas", "Moodle", "Coursera",
    "Udemy", "Skillshare", "MasterClass", "Khan Academy", "Pluralsight",
    "LinkedIn Learning", "Skillsoft", "Chegg", "Tutor.com", "Wyzant",
  ],
  hospitality: [
    "Marriott", "Hilton", "IHG", "Booking.com", "Expedia",
    "Agoda", "TravelPerk", "Concur", "Amadeus", "Sabre",
    "Oracle PMS", "SailPoint", "Fosse", "RoomRaccoon", "Mews",
  ],
  retail: [
    "Shopify", "WooCommerce", "Magento", "BigCommerce", "Salesforce Commerce",
    "SAP Commerce", "Adobe Commerce", "Square", "Stripe", "PayPal",
    "Zuora", "Avalara", "NetSuite", "Infor", "Cin7",
  ],
  foodAndBeverage: [
    "Toast POS", "Square", "TouchBistro", "MarginEdge", "BlueCart",
    "Uber Eats API", "DoorDash API", "Grubhub API", "Yelp", "OpenTable",
    "Resy", "Eventbrite", "Sevenrooms", "Toast", "Lightspeed",
  ],
  entertainment: [
    "Ticketmaster", "Eventbrite", "Tixjam", "Brown Paper Tickets", "ReserveBar",
    "ETIX", "TicketsNow", "StubHub", "Vivid Seats", "Tickpick",
    "SeatGeek", "LiveXLive", "Remo", "Amiando", "AXS",
  ],
  transportation: [
    "Google Maps", "Mapbox", "HERE", "Uber API", "Lyft API",
    "Waze", "TomTom", "ArcGIS", "Esri", "INRIX",
    "HERE Routing", "OpenStreetMap", "Mapillary", "Vroom", "Locus",
  ],
  enterprise: [
    "Salesforce", "HubSpot", "Microsoft Dynamics", "SAP", "Oracle",
    "NetSuite", "ServiceNow", "Workday", "Slack", "Microsoft Teams",
  ],
};
