// ZIVO AI Feature Catalog – Features 21-40

export interface Feature {
  id: number;
  name: string;
  description: string;
  capabilities: string[];
  category: string;
}

export const FEATURES: Feature[] = [
  {
    id: 21,
    name: "Mobile-First Framework",
    description: "Cross-platform mobile development with React Native and Flutter support.",
    capabilities: [
      "React Native integration",
      "Flutter support",
      "Cross-platform UI components",
      "Mobile optimization",
      "Touch interactions & gestures",
      "Mobile analytics",
      "App store deployment automation",
      "PWA (Progressive Web App) support",
      "Mobile testing framework",
      "Native module integration",
    ],
    category: "Mobile",
  },
  {
    id: 22,
    name: "Video/Stream Processing",
    description: "Full-featured video generation, transcoding, and streaming pipeline.",
    capabilities: [
      "Video generation engine",
      "Real-time stream processing",
      "Live transcoding",
      "HLS/DASH protocol support",
      "Automatic subtitle generation",
      "Video analytics tracking",
      "Thumbnail extraction",
      "Frame manipulation",
      "Video compression",
      "Streaming CDN integration",
    ],
    category: "Media",
  },
  {
    id: 23,
    name: "Voice & Audio",
    description: "Speech recognition, text-to-speech, and full audio processing pipeline.",
    capabilities: [
      "Speech recognition engine",
      "Text-to-speech synthesis",
      "Audio processing pipeline",
      "Voice command system",
      "Podcast generation",
      "Sound effects library",
      "Audio mixing & mastering",
      "Noise cancellation",
      "Audio visualization",
      "Speech analytics",
    ],
    category: "Media",
  },
  {
    id: 24,
    name: "Web3 & Blockchain",
    description: "Smart contracts, NFTs, DeFi, and complete Web3 wallet integration.",
    capabilities: [
      "Smart contract generation",
      "Web3 wallet integration",
      "NFT creation & management",
      "Token creation system",
      "DeFi protocol integration",
      "DAO governance setup",
      "Cryptocurrency payments",
      "Blockchain monitoring dashboard",
      "Transaction tracking",
      "Web3 authentication",
    ],
    category: "Blockchain",
  },
  {
    id: 25,
    name: "Social Features",
    description: "Complete social platform with auth, messaging, feeds, and real-time updates.",
    capabilities: [
      "User authentication system",
      "Social login (Google, GitHub, etc.)",
      "Comments & discussions",
      "Notifications system",
      "Follow/subscribe mechanics",
      "Direct messaging",
      "Activity feeds",
      "Real-time updates",
      "Social sharing",
      "User profiles",
    ],
    category: "Social",
  },
  {
    id: 26,
    name: "Design System",
    description: "Component library, design tokens, theming, and Figma integration.",
    capabilities: [
      "Component template library",
      "Design tokens management",
      "Theming system",
      "Brand guidelines",
      "Accessibility standards",
      "Design documentation",
      "Figma integration",
      "Design handoff tools",
      "Component variations",
      "Design tokens API",
    ],
    category: "Design",
  },
  {
    id: 27,
    name: "Advanced Analytics",
    description: "User journey tracking, funnel analysis, A/B testing, and real-time insights.",
    capabilities: [
      "User journey tracking",
      "Funnel analysis",
      "Retention metrics",
      "Cohort analysis",
      "A/B testing framework",
      "Heat mapping",
      "Session recording",
      "Custom dashboards",
      "Data export",
      "Real-time insights",
    ],
    category: "Analytics",
  },
  {
    id: 28,
    name: "Notification Engine",
    description: "Multi-channel notifications: email, SMS, push, Slack, and webhooks.",
    capabilities: [
      "Email notifications",
      "SMS alerts",
      "Push notifications",
      "In-app messaging",
      "Slack integration",
      "Webhook system",
      "Notification scheduling",
      "Delivery tracking",
      "Template builder",
      "Multi-channel support",
    ],
    category: "Communication",
  },
  {
    id: 29,
    name: "Payment Processing",
    description: "Stripe, PayPal, Apple/Google Pay, subscriptions, and revenue analytics.",
    capabilities: [
      "Stripe integration",
      "PayPal support",
      "Apple Pay/Google Pay",
      "Invoice generation",
      "Subscription management",
      "Refund handling",
      "Tax calculation",
      "Revenue analytics",
      "Payment history",
      "Currency conversion",
    ],
    category: "Payments",
  },
  {
    id: 30,
    name: "Localization (i18n)",
    description: "Multi-language support (50+ languages), RTL, currency, and regional formatting.",
    capabilities: [
      "Multi-language support (50+)",
      "Currency conversion",
      "Timezone handling",
      "Regional formatting",
      "Translation management",
      "RTL (Right-to-Left) support",
      "Language detection",
      "Content localization",
      "Date/time formatting",
      "Regional compliance",
    ],
    category: "Globalization",
  },
  {
    id: 31,
    name: "Advanced Authentication",
    description: "OAuth2, 2FA, biometrics, SAML, passwordless, and RBAC.",
    capabilities: [
      "OAuth2/OpenID Connect",
      "Two-factor authentication (2FA)",
      "Biometric authentication",
      "Social login providers",
      "SAML integration",
      "Session management",
      "Passwordless authentication",
      "JWT tokens",
      "API key management",
      "Role-based access control",
    ],
    category: "Security",
  },
  {
    id: 32,
    name: "Email Management",
    description: "Template builder, bulk sending, scheduling, A/B testing, and automation.",
    capabilities: [
      "Email template builder",
      "Bulk sending",
      "Email scheduling",
      "A/B testing",
      "Delivery analytics",
      "SMTP integration",
      "Email automation workflows",
      "Unsubscribe management",
      "SPF/DKIM/DMARC support",
      "Email tracking",
    ],
    category: "Communication",
  },
  {
    id: 33,
    name: "ChatBot Builder",
    description: "Conversational UI, intent recognition, dialogue flow, and human handoff.",
    capabilities: [
      "Conversational UI",
      "Intent recognition",
      "Entity extraction",
      "Dialogue flow designer",
      "Bot training system",
      "Multi-language chatbots",
      "App integration",
      "Analytics dashboard",
      "Human handoff",
      "Sentiment analysis",
    ],
    category: "AI",
  },
  {
    id: 34,
    name: "Maps & Location",
    description: "Google Maps, geolocation, route optimization, geo-fencing, and real-time tracking.",
    capabilities: [
      "Google Maps integration",
      "Geolocation services",
      "Route optimization",
      "Distance calculation",
      "Geocoding services",
      "Location-based services",
      "Map customization",
      "Real-time tracking",
      "Location history",
      "Geo-fencing",
    ],
    category: "Location",
  },
  {
    id: 35,
    name: "Data Visualization",
    description: "20+ chart types, dashboards, 3D visualizations, and export capabilities.",
    capabilities: [
      "Chart library (20+ chart types)",
      "Dashboard builder",
      "Real-time graphs",
      "Heatmaps",
      "Network diagrams",
      "3D visualizations",
      "Export capabilities (PDF, PNG, SVG)",
      "Custom widgets",
      "Interactive dashboards",
      "Data filtering",
    ],
    category: "Analytics",
  },
  {
    id: 36,
    name: "Gaming Elements",
    description: "Gamification: points, badges, leaderboards, achievements, and multiplayer support.",
    capabilities: [
      "Gamification system",
      "Points/badges/leaderboards",
      "Achievements system",
      "Progress tracking",
      "Challenges & quests",
      "Rewards system",
      "Multiplayer support",
      "Game analytics",
      "Leaderboards API",
      "Social sharing",
    ],
    category: "Engagement",
  },
  {
    id: 37,
    name: "Healthcare Integration",
    description: "HIPAA compliance, EHR, telemedicine, DICOM, and patient records.",
    capabilities: [
      "HIPAA compliance",
      "Patient records system",
      "Appointment scheduling",
      "Medical imaging support",
      "Prescription management",
      "Telemedicine support",
      "Health data integration",
      "Compliance reporting",
      "EHR compatibility",
      "DICOM support",
    ],
    category: "Healthcare",
  },
  {
    id: 38,
    name: "Enterprise Features",
    description: "SSO/SAML, audit logging, multi-tenancy, SOC2/ISO27001, and disaster recovery.",
    capabilities: [
      "SSO/SAML integration",
      "Advanced permissions",
      "Audit logging",
      "Data governance",
      "Compliance frameworks (SOC2, ISO27001)",
      "White-label options",
      "Multi-tenancy support",
      "SLA monitoring",
      "Enterprise support",
      "Backup & disaster recovery",
    ],
    category: "Enterprise",
  },
  {
    id: 39,
    name: "Logistics/Delivery",
    description: "Route planning, fleet management, real-time tracking, and dispatch system.",
    capabilities: [
      "Route planning & optimization",
      "Real-time tracking",
      "Driver management",
      "Fleet optimization",
      "Delivery scheduling",
      "Customer notifications",
      "Cost analytics",
      "Integration APIs",
      "Proof of delivery",
      "Dispatch system",
    ],
    category: "Logistics",
  },
  {
    id: 40,
    name: "Learning Management",
    description: "Course builder, student management, quizzes, certificates, and grading.",
    capabilities: [
      "Course builder",
      "Student management",
      "Quiz/assessment tools",
      "Certificate generation",
      "Progress tracking",
      "Content library",
      "Discussion forums",
      "Certification tracking",
      "Grading system",
      "Student analytics",
    ],
    category: "Education",
  },
];

export function getFeatureById(id: number): Feature | undefined {
  return FEATURES.find((f) => f.id === id);
}

export function getFeaturesByCategory(category: string): Feature[] {
  return FEATURES.filter((f) => f.category === category);
}

export function getAllCategories(): string[] {
  return [...new Set(FEATURES.map((f) => f.category))];
}
