export interface PlatformFeature {
  id: string;
  name: string;
  description: string;
}

export interface Platform {
  id: string;
  number: number;
  name: string;
  description: string;
  icon: string;
  features: PlatformFeature[];
  integrationCategory: string;
}

export const PLATFORMS: Platform[] = [
  {
    id: "healthcare",
    number: 41,
    name: "Healthcare AI Platform",
    description: "Advanced medical diagnostics and patient care management powered by AI",
    icon: "🏥",
    integrationCategory: "healthcare",
    features: [
      { id: "diagnostics", name: "Advanced Medical Diagnostics", description: "AI-powered diagnosis from symptoms and test results" },
      { id: "symptom-analysis", name: "AI Symptom Analysis", description: "Natural language symptom checker with differential diagnosis" },
      { id: "patient-records", name: "Patient Records Management", description: "Secure storage and retrieval of patient health records" },
      { id: "telemedicine", name: "Telemedicine Infrastructure", description: "Video consultations and remote patient monitoring" },
      { id: "medical-imaging", name: "Medical Imaging AI", description: "AI analysis of X-rays, MRIs, and CT scans" },
      { id: "prescriptions", name: "Prescription Management", description: "Digital prescriptions with drug interaction checks" },
      { id: "health-monitoring", name: "Health Monitoring", description: "Continuous vital sign tracking and alerts" },
      { id: "doctor-scheduling", name: "Doctor Scheduling", description: "Appointment booking and calendar management" },
      { id: "medical-billing", name: "Medical Billing", description: "Automated billing, coding, and claims processing" },
      { id: "hipaa", name: "HIPAA Compliance Automation", description: "Automated compliance checks and audit trails" },
      { id: "ehr", name: "Electronic Health Records (EHR)", description: "Interoperable EHR system with HL7/FHIR support" },
      { id: "lab-results", name: "Lab Result Analysis", description: "AI interpretation of laboratory test results" },
      { id: "insurance", name: "Insurance Integration", description: "Real-time insurance verification and claims submission" },
      { id: "research", name: "Medical Research Tools", description: "Clinical trial management and research data analysis" },
      { id: "analytics", name: "Healthcare Analytics", description: "Population health insights and outcome tracking" },
    ],
  },
  {
    id: "real-estate",
    number: 42,
    name: "Real Estate Platform",
    description: "Complete property management and transaction platform with AI valuation",
    icon: "🏠",
    integrationCategory: "real-estate",
    features: [
      { id: "listings", name: "Property Listing Management", description: "Create and manage property listings with rich media" },
      { id: "virtual-tours", name: "Virtual Tours (3D/VR)", description: "Immersive 3D and VR property walkthroughs" },
      { id: "mls", name: "MLS Integration", description: "Sync listings with Multiple Listing Service networks" },
      { id: "valuation", name: "Property Valuation AI", description: "Automated property valuation using comparable sales" },
      { id: "mortgage", name: "Mortgage Calculator", description: "Advanced mortgage and affordability calculations" },
      { id: "agents", name: "Agent Management", description: "Agent profiles, territories, and performance tracking" },
      { id: "crm", name: "Client CRM", description: "Buyer and seller relationship management" },
      { id: "documents", name: "Document Management", description: "Digital document storage and e-signature workflows" },
      { id: "contracts", name: "Contract Generation", description: "Automated real estate contract drafting" },
      { id: "escrow", name: "Escrow Management", description: "Digital escrow tracking and closing coordination" },
      { id: "inspections", name: "Property Inspections", description: "Schedule and track property inspection reports" },
      { id: "market-analysis", name: "Market Analysis", description: "Real-time market trends and comparable analysis" },
      { id: "investment", name: "Investment Calculator", description: "ROI, cap rate, and cash flow analysis tools" },
      { id: "tenant", name: "Tenant Management", description: "Lease management and rent collection" },
      { id: "maintenance", name: "Maintenance Tracking", description: "Work order management and vendor coordination" },
    ],
  },
  {
    id: "travel",
    number: 43,
    name: "Travel & Bookings",
    description: "End-to-end travel planning and booking management platform",
    icon: "✈️",
    integrationCategory: "travel",
    features: [
      { id: "flights", name: "Flight Search & Booking", description: "Real-time flight search with price comparison" },
      { id: "hotels", name: "Hotel Management", description: "Hotel inventory, booking, and rate management" },
      { id: "car-rental", name: "Car Rental Integration", description: "Vehicle rental booking and fleet management" },
      { id: "itinerary", name: "Travel Itinerary Builder", description: "AI-powered personalized trip planning" },
      { id: "visa", name: "Visa Requirements", description: "Country-specific visa and entry requirement lookup" },
      { id: "travel-insurance", name: "Travel Insurance", description: "Policy comparison, purchase, and claims" },
      { id: "currency", name: "Currency Converter", description: "Real-time exchange rates and multi-currency support" },
      { id: "price-tracking", name: "Flight Price Tracking", description: "Price alerts and fare prediction" },
      { id: "hotel-reviews", name: "Hotel Reviews Integration", description: "Aggregated reviews from multiple platforms" },
      { id: "confirmations", name: "Booking Confirmations", description: "Automated confirmation and reminder system" },
      { id: "travel-alerts", name: "Travel Alerts", description: "Safety advisories and travel disruption notifications" },
      { id: "luggage", name: "Luggage Tracking", description: "Real-time baggage tracking and lost luggage reporting" },
      { id: "expenses", name: "Travel Expenses", description: "Expense reporting and receipt management" },
      { id: "group-bookings", name: "Group Bookings", description: "Coordinated group travel management" },
      { id: "insurance-claims", name: "Travel Insurance Claims", description: "Automated claims filing and status tracking" },
    ],
  },
  {
    id: "social-network",
    number: 44,
    name: "Social Network",
    description: "Full-featured social platform with AI-powered content moderation and recommendations",
    icon: "👥",
    integrationCategory: "social-media",
    features: [
      { id: "profiles", name: "User Profiles", description: "Rich user profiles with customizable themes" },
      { id: "follow", name: "Friend/Follow System", description: "Bidirectional friendship and one-way follow relationships" },
      { id: "feeds", name: "Posts & Feeds", description: "Algorithmic and chronological content feeds" },
      { id: "notifications", name: "Real-time Notifications", description: "WebSocket-powered instant notifications" },
      { id: "messaging", name: "Direct Messaging", description: "End-to-end encrypted private conversations" },
      { id: "groups", name: "Groups & Communities", description: "Topic-based community management" },
      { id: "events", name: "Event Creation", description: "Virtual and in-person event management" },
      { id: "live-streaming", name: "Live Streaming", description: "Real-time video broadcasting to followers" },
      { id: "stories", name: "Story/Ephemeral Content", description: "24-hour disappearing posts and stories" },
      { id: "hashtags", name: "Hashtags & Trending", description: "Discoverable content with trending topics" },
      { id: "search", name: "Search Functionality", description: "Full-text search across users, posts, and topics" },
      { id: "recommendations", name: "Content Recommendations", description: "AI-powered personalized content discovery" },
      { id: "privacy", name: "Privacy Controls", description: "Granular audience and visibility settings" },
      { id: "blocking", name: "Blocking/Reporting", description: "User safety tools and abuse reporting" },
      { id: "moderation", name: "Content Moderation", description: "AI-assisted content review and policy enforcement" },
    ],
  },
  {
    id: "video",
    number: 45,
    name: "Video Platform",
    description: "Scalable video hosting, streaming, and monetization infrastructure",
    icon: "🎬",
    integrationCategory: "video-platforms",
    features: [
      { id: "upload", name: "Video Upload & Processing", description: "Multi-format video ingestion and transcoding" },
      { id: "streaming", name: "Streaming Infrastructure", description: "Global CDN-powered video delivery" },
      { id: "abr", name: "Adaptive Bitrate (ABR)", description: "Dynamic quality adjustment for any connection" },
      { id: "player", name: "Video Player", description: "Embeddable player with custom branding" },
      { id: "playlists", name: "Playlist Management", description: "Curated and auto-generated video playlists" },
      { id: "analytics", name: "Video Analytics", description: "Engagement metrics, watch time, and audience insights" },
      { id: "recommendations", name: "Recommendation Engine", description: "ML-powered video recommendation system" },
      { id: "comments", name: "Comments & Interactions", description: "Threaded comments with reaction system" },
      { id: "live", name: "Live Streaming", description: "RTMP ingest and low-latency live broadcasting" },
      { id: "channels", name: "Channel Management", description: "Creator channel pages and subscription management" },
      { id: "monetization", name: "Monetization (Ads/Subscriptions)", description: "Pre-roll ads, channel memberships, and pay-per-view" },
      { id: "editing", name: "Video Editing Tools", description: "Browser-based trim, cut, and annotation tools" },
      { id: "thumbnails", name: "Thumbnail Generation", description: "AI-generated and custom thumbnail selection" },
      { id: "captions", name: "Transcription & Captions", description: "Auto-generated captions in multiple languages" },
      { id: "seo", name: "Video SEO", description: "Schema markup, sitemaps, and search optimization" },
    ],
  },
  {
    id: "music",
    number: 46,
    name: "Music Streaming",
    description: "Artist-first music platform with streaming, analytics, and royalty management",
    icon: "🎵",
    integrationCategory: "music-streaming",
    features: [
      { id: "upload", name: "Audio Upload & Processing", description: "Lossless audio ingestion and format normalization" },
      { id: "player", name: "Streaming Player", description: "Web and mobile audio player with offline support" },
      { id: "playlists", name: "Playlist Creation", description: "User-curated and collaborative playlists" },
      { id: "albums", name: "Album Management", description: "Full album release management with artwork" },
      { id: "artists", name: "Artist Profiles", description: "Artist pages with biography and discography" },
      { id: "recommendations", name: "Music Recommendations", description: "Taste-based music discovery engine" },
      { id: "search", name: "Search Functionality", description: "Full catalog search by song, artist, or album" },
      { id: "downloads", name: "Offline Downloads", description: "Cached audio for offline playback" },
      { id: "queue", name: "Queue Management", description: "Drag-and-drop play queue with history" },
      { id: "radio", name: "Radio Stations", description: "Seed-based endless radio generation" },
      { id: "lyrics", name: "Lyrics Display", description: "Synchronized lyrics with karaoke mode" },
      { id: "analytics", name: "Audio Analytics", description: "Stream counts, listener demographics, and trends" },
      { id: "royalties", name: "Royalty Tracking", description: "Per-stream royalty calculation and reporting" },
      { id: "licensing", name: "Licensing Management", description: "Sync licensing and rights management" },
      { id: "sharing", name: "Social Sharing", description: "Share clips and playlists to social platforms" },
    ],
  },
  {
    id: "jobs",
    number: 47,
    name: "Job Board Platform",
    description: "AI-powered recruitment platform connecting employers with top talent",
    icon: "💼",
    integrationCategory: "job-boards",
    features: [
      { id: "posting", name: "Job Posting System", description: "Rich job description editor with SEO optimization" },
      { id: "resumes", name: "Resume Management", description: "AI-parsed resume storage and search" },
      { id: "search", name: "Job Search Filters", description: "Advanced filtering by location, salary, skills, and more" },
      { id: "ats", name: "Application Tracking (ATS)", description: "Full applicant tracking workflow management" },
      { id: "interviews", name: "Interview Scheduling", description: "Calendar sync and automated interview coordination" },
      { id: "candidates", name: "Candidate Profiles", description: "Skills graph and career history profiles" },
      { id: "salary", name: "Salary Insights", description: "Market salary data by role, location, and experience" },
      { id: "reviews", name: "Company Reviews", description: "Anonymous employer reviews and culture ratings" },
      { id: "assessments", name: "Skills Assessment", description: "Coding challenges and skills verification tests" },
      { id: "matching", name: "Job Matching AI", description: "ML-powered candidate-to-job matching" },
      { id: "alerts", name: "Email Alerts", description: "Customizable job alert subscriptions" },
      { id: "status", name: "Application Status", description: "Real-time application progress tracking" },
      { id: "offers", name: "Offer Management", description: "Digital offer letters and acceptance workflow" },
      { id: "background", name: "Background Checks", description: "Integrated third-party background verification" },
      { id: "analytics", name: "Analytics Dashboard", description: "Hiring funnel metrics and time-to-hire analysis" },
    ],
  },
  {
    id: "marketplace",
    number: 48,
    name: "Multi-Vendor Marketplace",
    description: "White-label marketplace infrastructure with vendor management and payment splits",
    icon: "🛍️",
    integrationCategory: "e-commerce",
    features: [
      { id: "onboarding", name: "Seller Onboarding", description: "KYC verification and vendor profile setup" },
      { id: "products", name: "Product Management", description: "Catalog management with variants and media" },
      { id: "inventory", name: "Inventory Tracking", description: "Real-time stock levels and reorder alerts" },
      { id: "orders", name: "Order Management", description: "End-to-end order processing and fulfillment" },
      { id: "payment-splits", name: "Payment Splits", description: "Automated revenue splitting between vendors" },
      { id: "commissions", name: "Commission System", description: "Configurable commission tiers and schedules" },
      { id: "vendor-analytics", name: "Vendor Analytics", description: "Sales, traffic, and conversion metrics per vendor" },
      { id: "disputes", name: "Dispute Resolution", description: "Buyer-seller dispute mediation workflow" },
      { id: "reviews", name: "Review System", description: "Verified purchase reviews with moderation" },
      { id: "seller-ratings", name: "Seller Ratings", description: "Aggregate seller performance scoring" },
      { id: "shipping", name: "Shipping Integration", description: "Multi-carrier shipping rate and label generation" },
      { id: "returns", name: "Return Management", description: "RMA workflow and refund processing" },
      { id: "bulk", name: "Bulk Operations", description: "Mass product import/export and price updates" },
      { id: "vendor-chat", name: "Vendor Chat", description: "Buyer-to-seller messaging system" },
      { id: "performance", name: "Performance Metrics", description: "Seller scorecards and quality benchmarks" },
    ],
  },
  {
    id: "saas-factory",
    number: 49,
    name: "SaaS Factory",
    description: "Auto-generate production-ready SaaS applications from templates and AI prompts",
    icon: "⚙️",
    integrationCategory: "saas-tools",
    features: [
      { id: "auto-generate", name: "Auto-generate SaaS Apps", description: "AI-driven full-stack application scaffolding" },
      { id: "templates", name: "Template Library", description: "100+ pre-built SaaS application templates" },
      { id: "components", name: "Component Builder", description: "Drag-and-drop UI component composer" },
      { id: "workflows", name: "Workflow Automation", description: "Visual workflow builder with triggers and actions" },
      { id: "db-schema", name: "Database Schema Generation", description: "AI-generated database models from descriptions" },
      { id: "api-gen", name: "API Generation", description: "Auto-generated REST and GraphQL APIs" },
      { id: "user-mgmt", name: "User Management", description: "Authentication, roles, and permissions system" },
      { id: "billing", name: "Billing System", description: "Subscription management and usage-based billing" },
      { id: "auth", name: "Authentication", description: "OAuth, SSO, and multi-factor authentication" },
      { id: "dashboard-builder", name: "Dashboard Builder", description: "Drag-and-drop analytics dashboard creator" },
      { id: "reports", name: "Report Generator", description: "Scheduled and on-demand report generation" },
      { id: "email-templates", name: "Email Templates", description: "Branded transactional and marketing email builder" },
      { id: "integrations-lib", name: "Integrations Library", description: "One-click third-party service connections" },
      { id: "deployment", name: "Deployment Automation", description: "CI/CD pipelines with one-click deploy" },
      { id: "multi-tenancy", name: "Multi-tenancy Setup", description: "Isolated tenant data and configuration management" },
    ],
  },
  {
    id: "advanced-features",
    number: 50,
    name: "Advanced Features Suite",
    description: "AI/ML, security, performance, DevOps, and analytics capabilities for any platform",
    icon: "🚀",
    integrationCategory: "saas-tools",
    features: [
      { id: "model-training", name: "Custom Model Training", description: "Fine-tune foundation models on your data" },
      { id: "computer-vision", name: "Computer Vision", description: "Image classification, object detection, and OCR" },
      { id: "nlp", name: "Natural Language Processing", description: "Text analysis, summarization, and generation" },
      { id: "e2e-encryption", name: "End-to-end Encryption", description: "Client-side encryption for all sensitive data" },
      { id: "threat-detection", name: "Threat Detection AI", description: "Real-time anomaly and intrusion detection" },
      { id: "auto-scaling", name: "Auto-scaling", description: "Dynamic resource allocation based on load" },
      { id: "cdn", name: "CDN Optimization", description: "Global edge caching and asset delivery" },
      { id: "iac", name: "Infrastructure as Code", description: "Terraform and Pulumi configuration templates" },
      { id: "containers", name: "Container Orchestration", description: "Kubernetes manifests and Helm charts" },
      { id: "ab-testing", name: "A/B Testing Infrastructure", description: "Experiment management and statistical analysis" },
      { id: "feature-flags", name: "Feature Flags", description: "Runtime feature toggling without deployments" },
      { id: "real-time-dashboards", name: "Real-time Dashboards", description: "Live metrics with sub-second refresh" },
      { id: "etl", name: "ETL Pipelines", description: "Data ingestion, transformation, and loading" },
      { id: "churn-prediction", name: "Churn Prediction", description: "ML model to predict and prevent customer churn" },
      { id: "gdpr", name: "GDPR/CCPA Tools", description: "Consent management and data subject request automation" },
    ],
  },
];

export function getPlatformById(id: string): Platform | undefined {
  return PLATFORMS.find((p) => p.id === id);
}

export function getPlatformByNumber(number: number): Platform | undefined {
  return PLATFORMS.find((p) => p.number === number);
}
