// Service Ecosystem Catalog
// Defines all 9 service categories, their features, and integrations.

export interface ServiceFeature {
  id: string;
  label: string;
}

export interface ServiceIntegration {
  name: string;
  url?: string;
}

export interface ServiceCategory {
  id: string;
  number: number;
  title: string;
  description: string;
  icon: string;
  features: ServiceFeature[];
  integrations: ServiceIntegration[];
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "grocery-delivery",
    number: 61,
    title: "Grocery Delivery",
    description: "Amazon Fresh-style grocery delivery platform",
    icon: "🛒",
    features: [
      { id: "store-integration", label: "Grocery store integration" },
      { id: "product-catalog", label: "Product catalog management" },
      { id: "realtime-inventory", label: "Real-time inventory" },
      { id: "price-management", label: "Price management" },
      { id: "weekly-deals", label: "Weekly deals & promotions" },
      { id: "produce-quality", label: "Produce quality standards" },
      { id: "expiration-tracking", label: "Expiration date tracking" },
      { id: "organic-filter", label: "Organic/local product filtering" },
      { id: "dietary-prefs", label: "Dietary preferences" },
      { id: "nutrition-info", label: "Nutrition information" },
      { id: "recipe-suggestions", label: "Recipe suggestions" },
      { id: "shopping-templates", label: "Shopping list templates" },
      { id: "one-click-reorder", label: "One-click reordering" },
      { id: "subscription-boxes", label: "Subscription boxes" },
      { id: "bulk-ordering", label: "Bulk ordering" },
      { id: "bulk-discounts", label: "Bulk discounts" },
      { id: "same-day-delivery", label: "Same-day delivery" },
      { id: "scheduled-delivery", label: "Scheduled delivery" },
      { id: "store-locator", label: "Store locator" },
      { id: "store-hours", label: "Store hours management" },
      { id: "payment-integration", label: "Payment integration" },
      { id: "loyalty-programs", label: "Loyalty programs" },
      { id: "customer-ratings", label: "Customer ratings" },
      { id: "product-reviews", label: "Product reviews" },
      { id: "stock-notifications", label: "Stock notifications" },
      { id: "pre-order", label: "Pre-order system" },
      { id: "return-refund", label: "Return/refund management" },
      { id: "quality-guarantees", label: "Quality guarantees" },
    ],
    integrations: [
      { name: "BigBasket" },
      { name: "Blinkit" },
      { name: "Dunzo" },
      { name: "Instacart" },
      { name: "Amazon Fresh" },
      { name: "Walmart+" },
      { name: "Target" },
      { name: "Kroger" },
      { name: "Ocado" },
      { name: "Getir" },
    ],
  },
  {
    id: "pharmacy-delivery",
    number: 62,
    title: "Pharmacy Delivery",
    description: "Medicine and prescription delivery platform",
    icon: "💊",
    features: [
      { id: "pharmacy-integration", label: "Pharmacy integration" },
      { id: "prescription-mgmt", label: "Prescription management" },
      { id: "prescription-upload", label: "Prescription upload" },
      { id: "doctor-econsult", label: "Doctor e-consultation" },
      { id: "prescription-verify", label: "Prescription verification" },
      { id: "med-reminders", label: "Medication reminders" },
      { id: "drug-interaction", label: "Drug interaction checker" },
      { id: "dosage-calc", label: "Dosage calculator" },
      { id: "side-effects", label: "Side effects information" },
      { id: "generic-alternatives", label: "Generic alternatives" },
      { id: "refill-automation", label: "Refill automation" },
      { id: "insurance-verify", label: "Insurance verification" },
      { id: "copay-calc", label: "Copay calculation" },
      { id: "bulk-med-order", label: "Bulk medication ordering" },
      { id: "chronic-condition", label: "Chronic condition management" },
      { id: "vaccination-tracking", label: "Vaccination tracking" },
      { id: "health-conditions", label: "Health conditions tracking" },
      { id: "med-history", label: "Medication history" },
      { id: "pharmacy-locator", label: "Pharmacy locator" },
      { id: "store-hours-ph", label: "Store hours" },
      { id: "stock-availability", label: "Stock availability" },
      { id: "express-delivery", label: "Express delivery" },
      { id: "cold-chain", label: "Cold chain management" },
      { id: "temp-monitoring", label: "Temperature monitoring" },
      { id: "tamper-proof", label: "Tamper-proof packaging" },
      { id: "signature-required", label: "Signature required" },
      { id: "pharmacist-chat", label: "Licensed pharmacist chat" },
      { id: "compliance-tracking", label: "Compliance tracking" },
      { id: "hipaa-compliance", label: "HIPAA compliance" },
      { id: "regulated-substances", label: "Regulated substance handling" },
    ],
    integrations: [
      { name: "CVS" },
      { name: "Walgreens" },
      { name: "Rite Aid" },
      { name: "Pharmacy Benefit Managers" },
      { name: "Insurance companies" },
      { name: "FDA database" },
      { name: "DrugBank" },
      { name: "PubMed" },
      { name: "Healthline" },
      { name: "WebMD" },
    ],
  },
  {
    id: "beauty-services",
    number: 63,
    title: "Beauty Services",
    description: "Salon & spa booking platform",
    icon: "💅",
    features: [
      { id: "salon-platform", label: "Salon/spa provider platform" },
      { id: "service-catalog-b", label: "Service catalog" },
      { id: "staff-mgmt", label: "Staff management" },
      { id: "stylist-profiles", label: "Stylist profiles" },
      { id: "before-after-photos", label: "Before/after photos" },
      { id: "service-pricing-b", label: "Service pricing" },
      { id: "package-deals-b", label: "Package deals" },
      { id: "membership-b", label: "Membership programs" },
      { id: "loyalty-rewards-b", label: "Loyalty rewards" },
      { id: "booking-calendar", label: "Booking calendar" },
      { id: "time-slots", label: "Time slot management" },
      { id: "cancellation-policy-b", label: "Cancellation policy" },
      { id: "rescheduling", label: "Rescheduling options" },
      { id: "customer-profiles-b", label: "Customer profiles" },
      { id: "service-prefs", label: "Service preferences" },
      { id: "allergies", label: "Allergies & sensitivities" },
      { id: "hair-type", label: "Hair type classification" },
      { id: "skin-type", label: "Skin type assessment" },
      { id: "beauty-consult", label: "Beauty consultation" },
      { id: "virtual-tryon", label: "Virtual try-on (AR)" },
      { id: "product-recs-b", label: "Product recommendations" },
      { id: "at-home-beauty", label: "At-home beauty services" },
      { id: "mobile-salon", label: "Mobile salon" },
      { id: "bridal-packages", label: "Bridal packages" },
      { id: "group-bookings", label: "Group bookings" },
      { id: "gift-cards-b", label: "Gift cards" },
      { id: "reviews-ratings-b", label: "Reviews & ratings" },
      { id: "stylist-ratings", label: "Stylist ratings" },
      { id: "service-ratings-b", label: "Service ratings" },
      { id: "photo-gallery-b", label: "Photo gallery" },
      { id: "video-testimonials", label: "Video testimonials" },
    ],
    integrations: [
      { name: "Treatwell" },
      { name: "Mindbody" },
      { name: "Schedulefly" },
      { name: "Sally Beauty" },
      { name: "Ulta" },
      { name: "Sephora" },
      { name: "ServiceTitan" },
      { name: "Zoho Bookings" },
      { name: "Acuity Scheduling" },
      { name: "Calendly" },
    ],
  },
  {
    id: "home-services",
    number: 64,
    title: "Home Services",
    description: "Cleaning, plumbing, repairs & more",
    icon: "🏠",
    features: [
      { id: "provider-network", label: "Service provider network" },
      { id: "service-categories-h", label: "Service categories" },
      { id: "pricing-structure-h", label: "Pricing structure" },
      { id: "availability-h", label: "Availability management" },
      { id: "background-verify", label: "Background verification" },
      { id: "insurance-verify-h", label: "Insurance verification" },
      { id: "license-verify", label: "License verification" },
      { id: "service-docs", label: "Service documentation" },
      { id: "before-after-h", label: "Before/after photos" },
      { id: "quote-system-h", label: "Quote system" },
      { id: "instant-booking-h", label: "Instant booking" },
      { id: "scheduled-booking-h", label: "Scheduled booking" },
      { id: "emergency-services", label: "Emergency services" },
      { id: "recurring-services", label: "Recurring services" },
      { id: "customer-comm", label: "Customer communication" },
      { id: "realtime-updates-h", label: "Real-time updates" },
      { id: "tech-tracking", label: "Technician tracking" },
      { id: "live-chat-h", label: "Live chat support" },
      { id: "service-history-h", label: "Service history" },
      { id: "warranty-tracking", label: "Warranty tracking" },
      { id: "parts-mgmt", label: "Parts management" },
      { id: "equipment-tracking", label: "Equipment tracking" },
      { id: "safety-compliance", label: "Safety compliance" },
      { id: "background-checks-h", label: "Background checks" },
      { id: "drug-screening", label: "Drug screening" },
      { id: "references-verify", label: "References verification" },
      { id: "customer-ratings-h", label: "Customer ratings" },
      { id: "feedback-system", label: "Feedback system" },
      { id: "photo-evidence", label: "Photo evidence" },
      { id: "quality-guarantee-h", label: "Quality guarantee" },
      { id: "money-back-guarantee", label: "Money-back guarantee" },
    ],
    integrations: [
      { name: "TaskRabbit" },
      { name: "Handy" },
      { name: "ServiceMaster" },
      { name: "Angie's List" },
      { name: "HomeAdvisor" },
      { name: "Thumbtack" },
      { name: "Care.com" },
      { name: "Porch" },
      { name: "ReviewStudio" },
      { name: "Google Home" },
    ],
  },
  {
    id: "pet-services",
    number: 65,
    title: "Pet Services",
    description: "Dog walking, pet sitting & care platform",
    icon: "🐾",
    features: [
      { id: "pet-owner-profiles", label: "Pet owner profiles" },
      { id: "pet-profiles", label: "Pet profiles (breed, age, health)" },
      { id: "provider-profiles-p", label: "Service provider profiles" },
      { id: "availability-cal-p", label: "Availability calendar" },
      { id: "recurring-bookings-p", label: "Recurring bookings" },
      { id: "one-time-bookings", label: "One-time bookings" },
      { id: "multi-pet-discounts", label: "Multiple pet discounts" },
      { id: "training-creds", label: "Training credentials" },
      { id: "certifications-p", label: "Certifications" },
      { id: "insurance-p", label: "Insurance coverage" },
      { id: "background-checks-p", label: "Background checks" },
      { id: "photo-updates", label: "Photo updates during service" },
      { id: "video-updates", label: "Video updates" },
      { id: "gps-tracking-p", label: "Real-time GPS tracking" },
      { id: "pet-health-tracking", label: "Pet health tracking" },
      { id: "vaccination-records", label: "Vaccination records" },
      { id: "medical-alerts", label: "Medical alerts" },
      { id: "dietary-prefs-p", label: "Dietary preferences" },
      { id: "behavior-notes", label: "Behavior notes" },
      { id: "pet-emergency", label: "Pet emergency contacts" },
      { id: "vet-integration", label: "Veterinary integration" },
      { id: "pet-med-tracking", label: "Pet medication tracking" },
      { id: "health-history-p", label: "Health history" },
      { id: "allergy-info-p", label: "Allergy information" },
      { id: "special-needs", label: "Special needs accommodations" },
      { id: "customer-ratings-p", label: "Customer ratings" },
      { id: "provider-ratings-p", label: "Service provider ratings" },
      { id: "reviews-photos-p", label: "Reviews with photos" },
      { id: "pet-photo-gallery", label: "Pet photo gallery" },
      { id: "social-features", label: "Social features (share pet photos)" },
      { id: "community-feed", label: "Community feed" },
    ],
    integrations: [
      { name: "Rover" },
      { name: "Wag" },
      { name: "Care.com Pets" },
      { name: "Petco" },
      { name: "PetSmart" },
      { name: "VCA Animal Hospital" },
      { name: "Banfield" },
      { name: "DVM360" },
      { name: "PetDesk" },
      { name: "Vetster" },
    ],
  },
  {
    id: "fitness-services",
    number: 66,
    title: "Fitness Services",
    description: "Trainer booking & fitness classes platform",
    icon: "💪",
    features: [
      { id: "fitness-platform", label: "Fitness provider platform" },
      { id: "trainer-profiles", label: "Trainer profiles" },
      { id: "certifications-f", label: "Certifications & credentials" },
      { id: "specialization", label: "Specialization areas" },
      { id: "class-scheduling", label: "Class scheduling" },
      { id: "group-classes", label: "Group classes" },
      { id: "personal-training", label: "Personal training" },
      { id: "class-types", label: "Class types (yoga, HIIT, CrossFit, etc.)" },
      { id: "difficulty-levels", label: "Difficulty levels" },
      { id: "duration-filter", label: "Duration filtering" },
      { id: "trainer-ratings-f", label: "Trainer ratings" },
      { id: "class-capacity", label: "Class capacity management" },
      { id: "booking-system-f", label: "Booking system" },
      { id: "waitlist", label: "Waitlist management" },
      { id: "cancellation-f", label: "Cancellation policy" },
      { id: "recurring-classes", label: "Recurring classes" },
      { id: "membership-plans", label: "Membership plans" },
      { id: "monthly-subs-f", label: "Monthly subscriptions" },
      { id: "class-passes", label: "Class passes" },
      { id: "trial-classes", label: "Trial classes" },
      { id: "package-deals-f", label: "Package deals" },
      { id: "referral-bonuses", label: "Referral bonuses" },
      { id: "progress-tracking-f", label: "Progress tracking" },
      { id: "workout-history", label: "Workout history" },
      { id: "fitness-goals", label: "Fitness goals" },
      { id: "body-metrics", label: "Body metrics tracking" },
      { id: "nutrition-guidance", label: "Nutrition guidance" },
      { id: "diet-recs", label: "Diet recommendations" },
      { id: "video-tutorials", label: "Video tutorials" },
      { id: "live-streaming", label: "Live streaming classes" },
      { id: "on-demand-classes", label: "On-demand classes" },
      { id: "virtual-training", label: "Virtual training" },
      { id: "hybrid-classes", label: "Hybrid classes (in-person + virtual)" },
    ],
    integrations: [
      { name: "ClassPass" },
      { name: "Peloton" },
      { name: "Apple Fitness+" },
      { name: "Nike Training Club" },
      { name: "Fitbit" },
      { name: "Strava" },
      { name: "MyFitnessPal" },
      { name: "Garmin" },
      { name: "Oura" },
      { name: "Headspace" },
    ],
  },
  {
    id: "tutoring",
    number: 67,
    title: "Tutoring",
    description: "Online education & tutoring platform",
    icon: "📚",
    features: [
      { id: "tutor-profiles", label: "Tutor profiles" },
      { id: "subject-expertise", label: "Subject expertise" },
      { id: "qualification-verify", label: "Qualification verification" },
      { id: "teaching-experience", label: "Teaching experience" },
      { id: "student-reviews", label: "Student reviews" },
      { id: "tutor-ratings", label: "Tutor ratings" },
      { id: "availability-cal-t", label: "Availability calendar" },
      { id: "session-scheduling", label: "Session scheduling" },
      { id: "one-on-one", label: "One-on-one tutoring" },
      { id: "group-tutoring", label: "Group tutoring" },
      { id: "class-scheduling-t", label: "Class scheduling" },
      { id: "learning-levels", label: "Learning levels (K-12, college, professional)" },
      { id: "subject-areas", label: "Subject areas" },
      { id: "language-tutoring", label: "Language tutoring" },
      { id: "test-prep", label: "Test prep (SAT, ACT, GRE, etc.)" },
      { id: "video-conferencing", label: "Video conferencing" },
      { id: "screen-sharing", label: "Screen sharing" },
      { id: "digital-whiteboard", label: "Digital whiteboard" },
      { id: "assignment-tracking", label: "Assignment tracking" },
      { id: "progress-reports", label: "Progress reports" },
      { id: "parent-portals", label: "Parent portals" },
      { id: "performance-metrics", label: "Student performance metrics" },
      { id: "curriculum-alignment", label: "Curriculum alignment" },
      { id: "learning-materials", label: "Learning materials" },
      { id: "resource-library", label: "Resource library" },
      { id: "homework-help", label: "Homework help" },
      { id: "exam-prep", label: "Exam preparation" },
      { id: "study-guides", label: "Study guides" },
      { id: "practice-tests", label: "Practice tests" },
      { id: "grade-tracking", label: "Grade tracking" },
      { id: "payment-billing-t", label: "Payment & billing" },
      { id: "session-recordings", label: "Session recordings" },
    ],
    integrations: [
      { name: "Tutor.com" },
      { name: "Chegg Tutors" },
      { name: "Wyzant" },
      { name: "Varsity Tutors" },
      { name: "Udemy" },
      { name: "Coursera" },
      { name: "Skillshare" },
      { name: "MasterClass" },
      { name: "Khan Academy" },
      { name: "Pluralsight" },
    ],
  },
  {
    id: "laundry-delivery",
    number: 68,
    title: "Laundry Delivery",
    description: "On-demand laundry & dry cleaning platform",
    icon: "👕",
    features: [
      { id: "laundry-platform", label: "Laundry provider platform" },
      { id: "service-pricing-l", label: "Service pricing" },
      { id: "weight-pricing", label: "Weight-based pricing" },
      { id: "express-service-l", label: "Express service" },
      { id: "same-day-l", label: "Same-day delivery" },
      { id: "next-day-l", label: "Next-day delivery" },
      { id: "dry-cleaning", label: "Dry cleaning" },
      { id: "ironing-service", label: "Ironing service" },
      { id: "stain-removal", label: "Stain removal" },
      { id: "alterations", label: "Alterations" },
      { id: "garment-care", label: "Garment care guide" },
      { id: "fabric-type", label: "Fabric type classification" },
      { id: "special-instructions-l", label: "Special instructions" },
      { id: "allergen-concerns", label: "Allergen concerns" },
      { id: "fragrance-prefs", label: "Fragrance preferences" },
      { id: "delivery-tracking-l", label: "Delivery tracking" },
      { id: "pickup-scheduling", label: "Pickup scheduling" },
      { id: "dropoff-locations", label: "Dropoff locations" },
      { id: "customer-portal-l", label: "Customer portal" },
      { id: "garment-tracking", label: "Garment tracking" },
      { id: "service-history-l", label: "Service history" },
      { id: "damage-claim", label: "Damage claim process" },
      { id: "insurance-l", label: "Insurance coverage" },
      { id: "loyalty-l", label: "Loyalty programs" },
      { id: "subscription-l", label: "Subscription options" },
      { id: "seasonal-services", label: "Seasonal services" },
      { id: "bulk-discounts-l", label: "Bulk discounts" },
      { id: "corporate-accounts", label: "Corporate accounts" },
      { id: "event-services", label: "Event services" },
      { id: "wedding-dress", label: "Wedding dress cleaning" },
      { id: "dry-cleaning-pricing", label: "Dry cleaning pricing" },
      { id: "eco-friendly", label: "Eco-friendly options" },
    ],
    integrations: [
      { name: "Rinse" },
      { name: "Zipjet" },
      { name: "Laundry Service" },
      { name: "Dhobi Express" },
      { name: "UrbanClap" },
      { name: "Justdial" },
      { name: "Google Maps" },
      { name: "Stripe" },
      { name: "PayPal" },
      { name: "Square" },
    ],
  },
  {
    id: "move-management",
    number: 69,
    title: "Move Management",
    description: "Full-service moving & relocation platform",
    icon: "🚛",
    features: [
      { id: "moving-platform", label: "Moving company platform" },
      { id: "service-types-m", label: "Service types (local, long-distance, international)" },
      { id: "inventory-mgmt-m", label: "Inventory management" },
      { id: "quote-system-m", label: "Quote system" },
      { id: "instant-quotes", label: "Instant quotes" },
      { id: "detailed-quotes", label: "Detailed quotes" },
      { id: "packing-services", label: "Packing services" },
      { id: "loading-unloading", label: "Loading/unloading" },
      { id: "transportation-m", label: "Transportation" },
      { id: "unpacking-services", label: "Unpacking services" },
      { id: "assembly-services", label: "Assembly services" },
      { id: "furniture-placement", label: "Furniture placement" },
      { id: "storage-services", label: "Storage services" },
      { id: "short-term-storage", label: "Short-term storage" },
      { id: "long-term-storage", label: "Long-term storage" },
      { id: "climate-storage", label: "Climate-controlled storage" },
      { id: "insurance-m", label: "Insurance options" },
      { id: "damage-liability", label: "Damage liability" },
      { id: "valuation-services", label: "Valuation services" },
      { id: "specialty-items", label: "Specialty items handling" },
      { id: "piano-moving", label: "Piano moving" },
      { id: "art-moving", label: "Art moving" },
      { id: "antique-moving", label: "Antique moving" },
      { id: "vehicle-transport", label: "Vehicle transportation" },
      { id: "realtime-tracking-m", label: "Real-time tracking" },
      { id: "gps-tracking-m", label: "GPS tracking" },
      { id: "driver-comm", label: "Driver communication" },
      { id: "move-day-updates", label: "Move day updates" },
      { id: "photo-docs", label: "Photo documentation" },
      { id: "delivery-confirm", label: "Delivery confirmation" },
      { id: "scheduling-flex", label: "Scheduling flexibility" },
      { id: "corporate-relocation", label: "Corporate relocation" },
      { id: "military-relocation", label: "Military relocation" },
      { id: "international-moving", label: "International moving" },
      { id: "customs-clearance", label: "Customs clearance" },
      { id: "documentation-m", label: "Documentation" },
    ],
    integrations: [],
  },
];

// Advanced feature groups (70)
export interface AdvancedFeatureGroup {
  id: string;
  title: string;
  features: string[];
}

export const ADVANCED_FEATURE_GROUPS: AdvancedFeatureGroup[] = [
  {
    id: "ai-ml",
    title: "AI/ML Advanced",
    features: [
      "Real-time demand prediction",
      "Dynamic pricing optimization",
      "Fraud detection",
      "Anomaly detection",
      "Recommendation engines",
      "Customer segmentation",
      "Predictive maintenance",
      "Churn prediction",
      "Lifetime value prediction",
      "Clustering algorithms",
      "Computer vision",
      "Image recognition",
      "Document processing",
      "Natural language processing",
    ],
  },
  {
    id: "enterprise",
    title: "Enterprise Features",
    features: [
      "White-label solutions",
      "Multi-brand management",
      "API marketplace",
      "Third-party integrations",
      "Custom workflows",
      "Workflow automation",
      "Business rules engine",
      "Advanced permissions",
      "Role-based access control",
      "Audit logging",
      "Compliance reporting",
      "Data governance",
      "Multi-tenancy",
      "SLA management",
    ],
  },
  {
    id: "analytics",
    title: "Advanced Analytics",
    features: [
      "Real-time dashboards",
      "Custom reports",
      "Data warehousing",
      "Business intelligence",
      "Predictive analytics",
      "Prescriptive analytics",
      "Data visualization",
      "ETL pipelines",
      "Data lake",
      "Real-time insights",
      "Historical trending",
      "Forecasting",
      "Revenue optimization",
      "Cost analysis",
    ],
  },
  {
    id: "marketplace",
    title: "Marketplace Features",
    features: [
      "Commission management",
      "Seller analytics",
      "Buyer analytics",
      "Transaction management",
      "Dispute resolution",
      "Escrow services",
      "Rating system",
      "Review moderation",
      "Seller verification",
      "Buyer verification",
      "Trust & safety",
    ],
  },
  {
    id: "payment-billing",
    title: "Payment & Billing",
    features: [
      "Multi-currency support",
      "Multiple payment methods",
      "Subscription billing",
      "Invoice management",
      "Expense tracking",
      "Tax calculation",
      "Financial reporting",
      "Revenue recognition",
      "Payout management",
      "Refund automation",
    ],
  },
  {
    id: "communication-support",
    title: "Communication & Support",
    features: [
      "Multi-channel support",
      "Chatbot integration",
      "AI-powered responses",
      "Ticket management",
      "Knowledge base",
      "FAQ system",
      "Community forums",
      "Video support",
      "Screen sharing",
      "Callback system",
    ],
  },
];

/**
 * Build a detailed system-prompt string for a service category,
 * suitable for injecting into the OpenAI generate-site request.
 */
export function buildServiceSystemPrompt(categoryId: string): string {
  const category = SERVICE_CATEGORIES.find((c) => c.id === categoryId);
  if (!category) return "";

  const featureList = category.features.map((f) => `- ${f.label}`).join("\n");
  const integrationList = category.integrations.map((i) => `- ${i.name}`).join("\n");

  return `You are generating a production-ready on-demand service platform for: ${category.title}.
Description: ${category.description}

Required features to incorporate:
${featureList}

Third-party integrations to support:
${integrationList}

Return clean, complete, production-quality HTML/CSS/JS code only. No explanations.`;
}
