// lib/plugins/prisma-plugin.ts — Auto-generates Prisma client after schema changes

import type { ZivoPlugin, GeneratedFile } from "./types";

function hasPrismaSchema(files: GeneratedFile[]): boolean {
  return files.some(
    (f) =>
      f.path.endsWith("schema.prisma") ||
      f.path.includes("prisma/schema")
  );
}

function generatePrismaSetup(files: GeneratedFile[]): GeneratedFile[] {
  const extras: GeneratedFile[] = [];

  if (!files.some((f) => f.path === "prisma/schema.prisma")) {
    // If generating a new schema, add a generate script helper
    extras.push({
      path: "scripts/prisma-generate.sh",
      content: `#!/bin/bash\n# Auto-generated by ZIVO AI Prisma Plugin\nnpx prisma generate\nnpx prisma db push\n`,
      action: "create",
    });
  }

  // Add Prisma singleton client if not already present
  const hasClient = files.some(
    (f) => f.path.includes("lib/prisma") || f.path.includes("lib/db")
  );
  if (!hasClient) {
    extras.push({
      path: "lib/prisma.ts",
      content: `import { PrismaClient } from "@prisma/client";\n\nconst globalForPrisma = globalThis as unknown as { prisma: PrismaClient };\n\nexport const prisma = globalForPrisma.prisma ?? new PrismaClient();\n\nif (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;\n`,
      action: "create",
    });
  }

  return extras;
}

export const prismaPlugin: ZivoPlugin = {
  name: "prisma-plugin",
  version: "1.0.0",
  description: "Auto-generates Prisma client and setup scripts after schema changes",
  hooks: {
    afterGenerate(files) {
      if (!hasPrismaSchema(files)) return files;
      const extras = generatePrismaSetup(files);
      return [...files, ...extras];
    },
  },
};
