// lib/plugins/shadcn-plugin.ts — Auto-installs ShadCN components referenced in generated code

import type { ZivoPlugin, GeneratedFile } from "./types";

const SHADCN_COMPONENTS = [
  "button", "card", "dialog", "dropdown-menu", "input", "label", "select",
  "sheet", "table", "tabs", "textarea", "toast", "tooltip", "badge",
  "checkbox", "radio-group", "switch", "slider", "progress", "avatar",
  "separator", "scroll-area", "popover", "command", "calendar", "form",
];

const SHADCN_IMPORT_PATTERN = /@\/components\/ui\/(\w[\w-]*)/g;

function detectShadcnComponents(files: GeneratedFile[]): string[] {
  const detected = new Set<string>();
  for (const file of files) {
    let match: RegExpExecArray | null;
    SHADCN_IMPORT_PATTERN.lastIndex = 0;
    while ((match = SHADCN_IMPORT_PATTERN.exec(file.content)) !== null) {
      const componentName = match[1].toLowerCase();
      if (SHADCN_COMPONENTS.includes(componentName)) {
        detected.add(componentName);
      }
    }
  }
  return Array.from(detected);
}

function generateInstallScript(components: string[]): GeneratedFile {
  const script = components.map((c) => `npx shadcn@latest add ${c}`).join("\n");
  return {
    path: "scripts/install-shadcn.sh",
    content: `#!/bin/bash\n# Auto-generated by ZIVO AI ShadCN Plugin\n# Run this script to install all required ShadCN components\n\n${script}\n`,
    action: "create",
  };
}

export const shadcnPlugin: ZivoPlugin = {
  name: "shadcn-plugin",
  version: "1.0.0",
  description: "Auto-detects and installs ShadCN UI components referenced in generated code",
  hooks: {
    afterGenerate(files) {
      const components = detectShadcnComponents(files);
      if (components.length === 0) return files;
      const installScript = generateInstallScript(components);
      return [...files, installScript];
    },
  },
  routes: [
    { path: "/api/plugins/shadcn", methods: ["GET"], description: "List available ShadCN components" },
  ],
};
