// lib/plugins/supabase-plugin.ts — Auto-creates Supabase table migration from schema

import type { ZivoPlugin, GeneratedFile } from "./types";

const SUPABASE_IMPORT_PATTERN = /@supabase\/supabase-js|createClient/;

function hasSupabaseCode(files: GeneratedFile[]): boolean {
  return files.some((f) => SUPABASE_IMPORT_PATTERN.test(f.content));
}

function extractTableNames(files: GeneratedFile[]): string[] {
  const tableNames = new Set<string>();
  const fromPattern = /\.from\(["'](\w+)["']\)/g;

  for (const file of files) {
    let match: RegExpExecArray | null;
    fromPattern.lastIndex = 0;
    while ((match = fromPattern.exec(file.content)) !== null) {
      tableNames.add(match[1]);
    }
  }

  return Array.from(tableNames);
}

function generateMigration(tables: string[]): GeneratedFile {
  const timestamp = new Date().toISOString().replace(/[^0-9]/g, "").slice(0, 14);
  const statements = tables
    .map(
      (table) => `-- Table: ${table}\nCREATE TABLE IF NOT EXISTS public.${table} (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  created_at timestamptz DEFAULT now() NOT NULL\n);\n\nALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY;\n`
    )
    .join("\n");

  return {
    path: `supabase/migrations/${timestamp}_auto_generated.sql`,
    content: `-- Auto-generated by ZIVO AI Supabase Plugin\n-- Review and modify before applying\n\n${statements}`,
    action: "create",
  };
}

export const supabasePlugin: ZivoPlugin = {
  name: "supabase-plugin",
  version: "1.0.0",
  description: "Auto-generates Supabase migration files for tables detected in generated code",
  hooks: {
    afterGenerate(files) {
      if (!hasSupabaseCode(files)) return files;

      const tables = extractTableNames(files);
      if (tables.length === 0) return files;

      const migration = generateMigration(tables);
      return [...files, migration];
    },
  },
};
