"use client";

import { useState } from "react";
import { Plus, Trash2, Download, Upload, Wand2 } from "lucide-react";
import SchemaVisualizer, { type SchemaTableDef, type SchemaField } from "../../components/SchemaVisualizer";

// ─── Types ────────────────────────────────────────────────────────────────────

const FIELD_TYPES = [
  "String",
  "Int",
  "BigInt",
  "Float",
  "Decimal",
  "Boolean",
  "DateTime",
  "Json",
  "Bytes",
];

type ExportFormat = "prisma" | "drizzle" | "sql";

// ─── Schema generation helpers ────────────────────────────────────────────────

function generatePrismaSchema(tables: SchemaTableDef[]): string {
  const header = `// Generated by ZIVO AI Schema Designer
// https://www.prisma.io/docs/concepts/components/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;
  const models = tables
    .map((t) => {
      const fields = t.fields.map((f) => {
        const parts = [
          `  ${f.name}`,
          `${f.type}${f.required ? "" : "?"}`,
          f.primaryKey ? "@id @default(cuid())" : "",
          f.unique && !f.primaryKey ? "@unique" : "",
          f.foreignKey ? `// FK → ${f.foreignKey}` : "",
        ]
          .filter(Boolean)
          .join(" ");
        return parts;
      });
      return `model ${t.name} {\n${fields.join("\n")}\n}`;
    })
    .join("\n\n");
  return header + models;
}

function generateDrizzleSchema(tables: SchemaTableDef[]): string {
  const typeMap: Record<string, string> = {
    String: "text",
    Int: "integer",
    BigInt: "bigint",
    Float: "real",
    Decimal: "decimal",
    Boolean: "boolean",
    DateTime: "timestamp",
    Json: "jsonb",
    Bytes: "bytea",
  };

  const imports = `import { pgTable, text, integer, bigint, real, decimal, boolean, timestamp, jsonb, bytea } from "drizzle-orm/pg-core";

`;
  const tables_ = tables
    .map((t) => {
      const cols = t.fields.map((f) => {
        const drizzleType = typeMap[f.type] ?? "text";
        const opts: string[] = [];
        if (f.primaryKey) opts.push(".primaryKey()");
        if (!f.required && !f.primaryKey) opts.push(".notNull(false)");
        if (f.unique) opts.push(".unique()");
        return `  ${f.name}: ${drizzleType}("${f.name}")${opts.join("")},`;
      });
      return `export const ${t.name.toLowerCase()} = pgTable("${t.name.toLowerCase()}", {\n${cols.join("\n")}\n});`;
    })
    .join("\n\n");
  return imports + tables_;
}

function generateSQLDDL(tables: SchemaTableDef[]): string {
  const typeMap: Record<string, string> = {
    String: "TEXT",
    Int: "INTEGER",
    BigInt: "BIGINT",
    Float: "REAL",
    Decimal: "DECIMAL(10,2)",
    Boolean: "BOOLEAN",
    DateTime: "TIMESTAMP WITH TIME ZONE",
    Json: "JSONB",
    Bytes: "BYTEA",
  };

  return tables
    .map((t) => {
      const cols = t.fields.map((f) => {
        const sqlType = typeMap[f.type] ?? "TEXT";
        const parts = [`  "${f.name}" ${sqlType}`];
        if (f.primaryKey) parts.push("PRIMARY KEY");
        if (f.required && !f.primaryKey) parts.push("NOT NULL");
        if (f.unique && !f.primaryKey) parts.push("UNIQUE");
        return parts.join(" ");
      });
      return `CREATE TABLE IF NOT EXISTS "${t.name}" (\n${cols.join(",\n")}\n);`;
    })
    .join("\n\n");
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function SchemaDesignerPage() {
  const [tables, setTables] = useState<SchemaTableDef[]>([
    {
      id: "1",
      name: "User",
      fields: [
        { name: "id", type: "String", required: true, unique: true, primaryKey: true },
        { name: "email", type: "String", required: true, unique: true },
        { name: "name", type: "String", required: false },
        { name: "createdAt", type: "DateTime", required: true },
      ],
    },
    {
      id: "2",
      name: "Post",
      fields: [
        { name: "id", type: "String", required: true, unique: true, primaryKey: true },
        { name: "title", type: "String", required: true },
        { name: "content", type: "String", required: false },
        { name: "authorId", type: "String", required: true, foreignKey: "User.id" },
        { name: "createdAt", type: "DateTime", required: true },
      ],
    },
  ]);

  const [exportFormat, setExportFormat] = useState<ExportFormat>("prisma");
  const [activeTab, setActiveTab] = useState<"designer" | "preview" | "visualizer">("designer");
  const [aiPrompt, setAiPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [importText, setImportText] = useState("");
  const [showImport, setShowImport] = useState(false);

  // ── Table operations ────────────────────────────────────────────────────────

  const addTable = () => {
    const id = Date.now().toString();
    setTables((prev) => [
      ...prev,
      { id, name: `Table${prev.length + 1}`, fields: [
        { name: "id", type: "String", required: true, unique: true, primaryKey: true },
      ] },
    ]);
  };

  const removeTable = (id: string) => {
    setTables((prev) => prev.filter((t) => t.id !== id));
  };

  const updateTableName = (id: string, name: string) => {
    setTables((prev) => prev.map((t) => (t.id === id ? { ...t, name } : t)));
  };

  // ── Field operations ────────────────────────────────────────────────────────

  const addField = (tableId: string) => {
    setTables((prev) =>
      prev.map((t) =>
        t.id === tableId
          ? {
              ...t,
              fields: [
                ...t.fields,
                { name: "newField", type: "String", required: false, unique: false },
              ],
            }
          : t
      )
    );
  };

  const updateField = (tableId: string, idx: number, field: Partial<SchemaField>) => {
    setTables((prev) =>
      prev.map((t) =>
        t.id === tableId
          ? {
              ...t,
              fields: t.fields.map((f, i) => (i === idx ? { ...f, ...field } : f)),
            }
          : t
      )
    );
  };

  const removeField = (tableId: string, idx: number) => {
    setTables((prev) =>
      prev.map((t) =>
        t.id === tableId
          ? { ...t, fields: t.fields.filter((_, i) => i !== idx) }
          : t
      )
    );
  };

  // ── Export ──────────────────────────────────────────────────────────────────

  const exportedSchema =
    exportFormat === "prisma"
      ? generatePrismaSchema(tables)
      : exportFormat === "drizzle"
      ? generateDrizzleSchema(tables)
      : generateSQLDDL(tables);

  const handleDownload = () => {
    const ext = exportFormat === "sql" ? "sql" : "ts";
    const filename = `schema.${exportFormat === "prisma" ? "prisma" : ext}`;
    const blob = new Blob([exportedSchema], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  // ── AI Generation ───────────────────────────────────────────────────────────

  const handleAIGenerate = async () => {
    if (!aiPrompt.trim()) return;
    setIsGenerating(true);
    try {
      const res = await fetch("/api/generate-database", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          orm: "prisma",
          database: "postgresql",
          models: aiPrompt,
        }),
      });
      if (!res.ok) throw new Error("Generation failed");
      const data = await res.json();
      // Find schema file and parse models from it
      const schemaFile = data.files?.find(
        (f: { path: string }) =>
          f.path.includes("schema.prisma") || f.path.includes("schema.ts")
      );
      if (schemaFile) {
        setImportText(schemaFile.content);
        setShowImport(true);
      }
    } catch (err) {
      console.error("[schema-designer] AI generation failed:", err);
    } finally {
      setIsGenerating(false);
    }
  };

  // ── Import (simple Prisma parser) ───────────────────────────────────────────

  const handleImport = () => {
    const newTables: SchemaTableDef[] = [];
    const modelRegex = /model\s+(\w+)\s*\{([^}]+)\}/g;
    let modelMatch: RegExpExecArray | null;
    while ((modelMatch = modelRegex.exec(importText)) !== null) {
      const modelName = modelMatch[1];
      const body = modelMatch[2];
      const fields: SchemaField[] = [];
      const fieldRegex = /^\s+(\w+)\s+([\w?]+)(.*?)$/gm;
      let fieldMatch: RegExpExecArray | null;
      while ((fieldMatch = fieldRegex.exec(body)) !== null) {
        const [, name, typeRaw, decorators] = fieldMatch;
        if (!name || name.startsWith("//") || name === "@@") continue;
        const isOptional = typeRaw.endsWith("?");
        const type = typeRaw.replace("?", "");
        const fieldTypeMapped =
          FIELD_TYPES.includes(type) ? type : "String";
        fields.push({
          name,
          type: fieldTypeMapped,
          required: !isOptional,
          unique: decorators?.includes("@unique") ?? false,
          primaryKey: decorators?.includes("@id") ?? false,
        });
      }
      newTables.push({ id: Date.now().toString() + newTables.length, name: modelName, fields });
    }
    if (newTables.length > 0) {
      setTables(newTables);
      setShowImport(false);
      setImportText("");
    }
  };

  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#0a0b14",
        color: "#f1f5f9",
        fontFamily: "'Inter','Segoe UI',system-ui,sans-serif",
        display: "flex",
        flexDirection: "column",
      }}
    >
      {/* Header */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "0 1.5rem",
          height: 52,
          borderBottom: "1px solid rgba(255,255,255,0.08)",
          background: "#0f1120",
          flexShrink: 0,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
          <a
            href="/dashboard"
            style={{
              display: "flex", alignItems: "center", gap: "0.5rem", textDecoration: "none",
            }}
          >
            <div
              style={{
                width: 28, height: 28,
                background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
                borderRadius: 8,
                display: "flex", alignItems: "center", justifyContent: "center",
                fontSize: 14, fontWeight: 700, color: "#fff",
              }}
            >
              Z
            </div>
            <span style={{ fontWeight: 700, fontSize: "1rem", color: "#f1f5f9" }}>ZIVO AI</span>
          </a>
          <span style={{ color: "#475569", fontSize: "0.8rem" }}>/ Schema Designer</span>
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
          <select
            value={exportFormat}
            onChange={(e) => setExportFormat(e.target.value as ExportFormat)}
            style={{
              background: "rgba(255,255,255,0.06)",
              border: "1px solid rgba(255,255,255,0.12)",
              borderRadius: 6,
              color: "#94a3b8",
              fontSize: "0.8rem",
              padding: "0.35rem 0.6rem",
            }}
          >
            <option value="prisma">Prisma</option>
            <option value="drizzle">Drizzle</option>
            <option value="sql">SQL DDL</option>
          </select>
          <button
            onClick={handleDownload}
            style={{
              display: "flex", alignItems: "center", gap: "0.4rem",
              padding: "0.35rem 0.75rem",
              background: "rgba(99,102,241,0.15)",
              border: "1px solid rgba(99,102,241,0.3)",
              borderRadius: 6,
              color: "#a5b4fc",
              fontSize: "0.8rem",
              cursor: "pointer",
            }}
          >
            <Download className="w-3.5 h-3.5" />
            Export
          </button>
          <button
            onClick={() => setShowImport(true)}
            style={{
              display: "flex", alignItems: "center", gap: "0.4rem",
              padding: "0.35rem 0.75rem",
              background: "rgba(255,255,255,0.05)",
              border: "1px solid rgba(255,255,255,0.1)",
              borderRadius: 6,
              color: "#94a3b8",
              fontSize: "0.8rem",
              cursor: "pointer",
            }}
          >
            <Upload className="w-3.5 h-3.5" />
            Import
          </button>
        </div>
      </div>

      {/* AI Prompt bar */}
      <div
        style={{
          padding: "0.75rem 1.5rem",
          borderBottom: "1px solid rgba(255,255,255,0.06)",
          background: "#0f1120",
          display: "flex",
          gap: "0.5rem",
          alignItems: "center",
        }}
      >
        <Wand2 className="w-4 h-4 text-indigo-400 shrink-0" />
        <input
          type="text"
          value={aiPrompt}
          onChange={(e) => setAiPrompt(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && handleAIGenerate()}
          placeholder="Describe your app to generate schema with AI… e.g. 'SaaS app with users, teams, projects, tasks'"
          style={{
            flex: 1,
            background: "transparent",
            border: "none",
            color: "#f1f5f9",
            fontSize: "0.875rem",
            outline: "none",
          }}
        />
        <button
          onClick={handleAIGenerate}
          disabled={isGenerating || !aiPrompt.trim()}
          style={{
            padding: "0.4rem 1rem",
            background: isGenerating ? "rgba(99,102,241,0.2)" : "linear-gradient(135deg,#6366f1,#8b5cf6)",
            border: "none",
            borderRadius: 6,
            color: "#fff",
            fontSize: "0.8rem",
            fontWeight: 600,
            cursor: isGenerating ? "default" : "pointer",
            opacity: isGenerating ? 0.7 : 1,
          }}
        >
          {isGenerating ? "Generating…" : "Generate"}
        </button>
      </div>

      {/* Tabs */}
      <div
        style={{
          display: "flex",
          gap: "0.25rem",
          padding: "0.5rem 1.5rem 0",
          background: "#0f1120",
          borderBottom: "1px solid rgba(255,255,255,0.06)",
        }}
      >
        {(["designer", "visualizer", "preview"] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            style={{
              padding: "0.4rem 1rem",
              borderRadius: "6px 6px 0 0",
              border: "none",
              background: activeTab === tab ? "#0a0b14" : "transparent",
              borderTop: activeTab === tab ? "1px solid rgba(99,102,241,0.4)" : "1px solid transparent",
              borderLeft: activeTab === tab ? "1px solid rgba(255,255,255,0.08)" : "1px solid transparent",
              borderRight: activeTab === tab ? "1px solid rgba(255,255,255,0.08)" : "1px solid transparent",
              color: activeTab === tab ? "#a5b4fc" : "#475569",
              fontSize: "0.8rem",
              fontWeight: activeTab === tab ? 600 : 400,
              cursor: "pointer",
              textTransform: "capitalize",
            }}
          >
            {tab}
          </button>
        ))}
        <div style={{ marginLeft: "auto", display: "flex", alignItems: "center" }}>
          <button
            onClick={addTable}
            style={{
              display: "flex", alignItems: "center", gap: "0.35rem",
              padding: "0.3rem 0.75rem",
              background: "linear-gradient(135deg,#6366f1,#8b5cf6)",
              border: "none",
              borderRadius: 6,
              color: "#fff",
              fontSize: "0.78rem",
              fontWeight: 600,
              cursor: "pointer",
              marginBottom: 4,
            }}
          >
            <Plus className="w-3.5 h-3.5" />
            Add Table
          </button>
        </div>
      </div>

      {/* Main content */}
      <div style={{ flex: 1, overflow: "hidden", display: "flex" }}>
        {/* Designer tab */}
        {activeTab === "designer" && (
          <div style={{ flex: 1, overflowY: "auto", padding: "1.25rem 1.5rem" }}>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))",
                gap: "1rem",
              }}
            >
              {tables.map((table) => (
                <div
                  key={table.id}
                  style={{
                    background: "#0f1120",
                    border: "1px solid rgba(255,255,255,0.08)",
                    borderRadius: 12,
                    overflow: "hidden",
                  }}
                >
                  {/* Table header */}
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "space-between",
                      padding: "0.6rem 0.75rem",
                      background: "rgba(99,102,241,0.15)",
                      borderBottom: "1px solid rgba(99,102,241,0.2)",
                    }}
                  >
                    <input
                      value={table.name}
                      onChange={(e) => updateTableName(table.id, e.target.value)}
                      style={{
                        background: "transparent",
                        border: "none",
                        color: "#a5b4fc",
                        fontSize: "0.875rem",
                        fontWeight: 700,
                        outline: "none",
                        flex: 1,
                      }}
                    />
                    <button
                      onClick={() => removeTable(table.id)}
                      style={{ background: "none", border: "none", cursor: "pointer", color: "#475569" }}
                    >
                      <Trash2 className="w-4 h-4 hover:text-red-400" />
                    </button>
                  </div>

                  {/* Column headers */}
                  <div
                    style={{
                      display: "grid",
                      gridTemplateColumns: "1fr 90px 80px auto",
                      gap: "0.25rem",
                      padding: "0.4rem 0.75rem",
                      borderBottom: "1px solid rgba(255,255,255,0.05)",
                    }}
                  >
                    {["Field", "Type", "Options", ""].map((h) => (
                      <span key={h} style={{ fontSize: "0.68rem", color: "#475569", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em" }}>
                        {h}
                      </span>
                    ))}
                  </div>

                  {/* Fields */}
                  <div style={{ padding: "0.5rem 0.75rem", display: "flex", flexDirection: "column", gap: "0.35rem" }}>
                    {table.fields.map((field, idx) => (
                      <div
                        key={idx}
                        style={{
                          display: "grid",
                          gridTemplateColumns: "1fr 90px 80px auto",
                          gap: "0.25rem",
                          alignItems: "center",
                        }}
                      >
                        <input
                          value={field.name}
                          onChange={(e) => updateField(table.id, idx, { name: e.target.value })}
                          style={{
                            background: "rgba(255,255,255,0.04)",
                            border: "1px solid rgba(255,255,255,0.08)",
                            borderRadius: 4,
                            color: "#e2e8f0",
                            fontSize: "0.78rem",
                            padding: "0.25rem 0.4rem",
                            outline: "none",
                            fontFamily: "monospace",
                          }}
                        />
                        <select
                          value={field.type}
                          onChange={(e) => updateField(table.id, idx, { type: e.target.value })}
                          style={{
                            background: "rgba(255,255,255,0.04)",
                            border: "1px solid rgba(255,255,255,0.08)",
                            borderRadius: 4,
                            color: "#818cf8",
                            fontSize: "0.75rem",
                            padding: "0.25rem",
                            outline: "none",
                          }}
                        >
                          {FIELD_TYPES.map((ft) => (
                            <option key={ft} value={ft}>{ft}</option>
                          ))}
                        </select>
                        <div style={{ display: "flex", gap: "0.35rem", justifyContent: "center" }}>
                          <label title="Required" style={{ cursor: "pointer", fontSize: "0.68rem", color: field.required ? "#a5b4fc" : "#475569" }}>
                            <input
                              type="checkbox"
                              checked={field.required ?? false}
                              onChange={(e) => updateField(table.id, idx, { required: e.target.checked })}
                              style={{ display: "none" }}
                            />
                            Req
                          </label>
                          <label title="Unique" style={{ cursor: "pointer", fontSize: "0.68rem", color: field.unique ? "#a5b4fc" : "#475569" }}>
                            <input
                              type="checkbox"
                              checked={field.unique ?? false}
                              onChange={(e) => updateField(table.id, idx, { unique: e.target.checked })}
                              style={{ display: "none" }}
                            />
                            Uniq
                          </label>
                          <label title="Primary Key" style={{ cursor: "pointer", fontSize: "0.68rem", color: field.primaryKey ? "#fbbf24" : "#475569" }}>
                            <input
                              type="checkbox"
                              checked={field.primaryKey ?? false}
                              onChange={(e) => updateField(table.id, idx, { primaryKey: e.target.checked })}
                              style={{ display: "none" }}
                            />
                            PK
                          </label>
                        </div>
                        <button
                          onClick={() => removeField(table.id, idx)}
                          style={{ background: "none", border: "none", cursor: "pointer", color: "#475569", padding: 0 }}
                        >
                          <Trash2 className="w-3.5 h-3.5 hover:text-red-400" />
                        </button>
                      </div>
                    ))}
                    <button
                      onClick={() => addField(table.id)}
                      style={{
                        display: "flex", alignItems: "center", gap: "0.25rem",
                        background: "none", border: "none",
                        color: "#6366f1",
                        fontSize: "0.75rem",
                        cursor: "pointer",
                        padding: "0.25rem 0",
                        marginTop: 2,
                      }}
                    >
                      <Plus className="w-3 h-3" />
                      Add Field
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Visualizer tab */}
        {activeTab === "visualizer" && (
          <div style={{ flex: 1, overflow: "auto", padding: "1.25rem 1.5rem" }}>
            <SchemaVisualizer tables={tables} />
          </div>
        )}

        {/* Preview tab */}
        {activeTab === "preview" && (
          <div style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" }}>
            <div style={{ padding: "0.5rem 1.5rem", borderBottom: "1px solid rgba(255,255,255,0.06)", display: "flex", gap: "0.5rem" }}>
              <span style={{ fontSize: "0.75rem", color: "#475569" }}>
                {exportFormat === "prisma" ? "schema.prisma" : exportFormat === "drizzle" ? "schema.ts" : "schema.sql"}
              </span>
            </div>
            <pre
              style={{
                flex: 1,
                margin: 0,
                padding: "1.25rem 1.5rem",
                overflow: "auto",
                fontSize: "0.8rem",
                fontFamily: "ui-monospace, monospace",
                color: "#94a3b8",
                lineHeight: 1.7,
                background: "transparent",
              }}
            >
              {exportedSchema}
            </pre>
          </div>
        )}
      </div>

      {/* Import modal */}
      {showImport && (
        <div
          style={{
            position: "fixed", inset: 0,
            background: "rgba(0,0,0,0.7)",
            display: "flex", alignItems: "center", justifyContent: "center",
            zIndex: 50,
          }}
          onClick={(e) => e.target === e.currentTarget && setShowImport(false)}
        >
          <div
            style={{
              background: "#0f1120",
              border: "1px solid rgba(255,255,255,0.1)",
              borderRadius: 12,
              padding: "1.5rem",
              width: "min(600px, 90vw)",
              display: "flex",
              flexDirection: "column",
              gap: "1rem",
            }}
          >
            <h2 style={{ margin: 0, fontSize: "1rem", fontWeight: 700 }}>Import Prisma Schema</h2>
            <p style={{ margin: 0, fontSize: "0.8rem", color: "#475569" }}>
              Paste a Prisma schema below to import its models into the designer.
            </p>
            <textarea
              value={importText}
              onChange={(e) => setImportText(e.target.value)}
              rows={12}
              placeholder="model User { ... }"
              style={{
                background: "rgba(255,255,255,0.03)",
                border: "1px solid rgba(255,255,255,0.1)",
                borderRadius: 8,
                color: "#94a3b8",
                fontSize: "0.8rem",
                fontFamily: "monospace",
                padding: "0.75rem",
                resize: "vertical",
                outline: "none",
              }}
            />
            <div style={{ display: "flex", gap: "0.5rem", justifyContent: "flex-end" }}>
              <button
                onClick={() => setShowImport(false)}
                style={{
                  padding: "0.4rem 1rem",
                  background: "rgba(255,255,255,0.05)",
                  border: "1px solid rgba(255,255,255,0.1)",
                  borderRadius: 6,
                  color: "#94a3b8",
                  fontSize: "0.8rem",
                  cursor: "pointer",
                }}
              >
                Cancel
              </button>
              <button
                onClick={handleImport}
                style={{
                  padding: "0.4rem 1rem",
                  background: "linear-gradient(135deg,#6366f1,#8b5cf6)",
                  border: "none",
                  borderRadius: 6,
                  color: "#fff",
                  fontSize: "0.8rem",
                  fontWeight: 600,
                  cursor: "pointer",
                }}
              >
                Import
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
