/**
 * POST /api/projects/[id]/publish/github
 *
 * Pushes all project files to a GitHub repository using a GitHub PAT.
 * Creates the repo if it does not exist. Stores the repo URL on the project.
 *
 * Body:
 *   repoName      — target repo name (created under the authenticated GitHub user)
 *   githubToken   — GitHub Personal Access Token (classic or fine-grained with repo scope)
 *   isPrivate     — (optional, default true)
 *   commitMessage — (optional)
 */
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { extractBearerToken, getUserFromToken, createAuthedClient } from '@/lib/db/projects-db';

export const runtime = 'nodejs';

interface RouteParams {
  params: Promise<{ id: string }>;
}

/** GitHub repository name: must start/end with alphanumeric; may contain dots, hyphens, underscores internally; or a single alphanumeric char. */
const GITHUB_REPO_NAME_REGEX = /^[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9]$|^[a-zA-Z0-9]$/;

const BodySchema = z.object({
  repoName: z
    .string()
    .min(1)
    .max(100)
    .regex(GITHUB_REPO_NAME_REGEX, 'Invalid repo name'),
  githubToken: z.string().min(1),
  isPrivate: z.boolean().optional().default(true),
  commitMessage: z.string().optional().default('feat: publish from ZIVO-AI'),
});

const GITHUB_API = 'https://api.github.com';

interface GithubRepoResponse {
  full_name: string;
  html_url: string;
  default_branch: string;
}

async function ghRequest<T>(
  path: string,
  options: RequestInit,
  pat: string
): Promise<T> {
  const res = await fetch(`${GITHUB_API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${pat}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
      ...(options.headers ?? {}),
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`GitHub API ${path} → ${res.status}: ${body}`);
  }
  return res.json() as Promise<T>;
}

export async function POST(req: Request, { params }: RouteParams) {
  const { id: projectId } = await params;

  const token = extractBearerToken(req.headers.get('Authorization'));
  if (!token) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const user = await getUserFromToken(token);
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  let rawBody: unknown;
  try {
    rawBody = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const parsed = BodySchema.safeParse(rawBody);
  if (!parsed.success) {
    return NextResponse.json({ error: 'Invalid request', details: parsed.error.flatten() }, { status: 400 });
  }

  const { repoName, githubToken, isPrivate, commitMessage } = parsed.data;

  const client = createAuthedClient(token);

  // Verify ownership
  const { data: project, error: projectError } = await client
    .from('projects')
    .select('id, title')
    .eq('id', projectId)
    .eq('owner_user_id', user.id)
    .single();

  if (projectError || !project) {
    return NextResponse.json({ error: 'Project not found' }, { status: 404 });
  }

  // Fetch project files
  const { data: files } = await client
    .from('project_files')
    .select('path, content')
    .eq('project_id', projectId);

  try {
    // Get GitHub user
    const ghUser = await ghRequest<{ login: string }>('/user', { method: 'GET' }, githubToken);
    const owner = ghUser.login;

    // Create repo if not existing
    let repo: GithubRepoResponse;
    try {
      repo = await ghRequest<GithubRepoResponse>(
        `/repos/${owner}/${repoName}`,
        { method: 'GET' },
        githubToken
      );
    } catch {
      repo = await ghRequest<GithubRepoResponse>(
        '/user/repos',
        {
          method: 'POST',
          body: JSON.stringify({
            name: repoName,
            description: `Generated by ZIVO-AI: ${(project as { title: string }).title}`,
            private: isPrivate,
            auto_init: true,
          }),
        },
        githubToken
      );
    }

    const branch = repo.default_branch || 'main';

    // Get latest commit + tree SHA
    const refData = await ghRequest<{ object: { sha: string } }>(
      `/repos/${owner}/${repoName}/git/ref/heads/${branch}`,
      { method: 'GET' },
      githubToken
    );
    const latestCommitSha = refData.object.sha;

    const commitData = await ghRequest<{ tree: { sha: string } }>(
      `/repos/${owner}/${repoName}/git/commits/${latestCommitSha}`,
      { method: 'GET' },
      githubToken
    );
    const baseTreeSha = commitData.tree.sha;

    // Build tree items
    const filesToPush = (files ?? []) as Array<{ path: string; content: string }>;
    const treeItems = await Promise.all(
      filesToPush.map(async (f) => {
        const blob = await ghRequest<{ sha: string }>(
          `/repos/${owner}/${repoName}/git/blobs`,
          {
            method: 'POST',
            body: JSON.stringify({
              content: Buffer.from(f.content).toString('base64'),
              encoding: 'base64',
            }),
          },
          githubToken
        );
        return { path: f.path, mode: '100644', type: 'blob', sha: blob.sha };
      })
    );

    if (treeItems.length === 0) {
      const readme = `# ${(project as { title: string }).title}\n\nGenerated by [ZIVO-AI](https://zivo.ai).\n`;
      const blob = await ghRequest<{ sha: string }>(
        `/repos/${owner}/${repoName}/git/blobs`,
        {
          method: 'POST',
          body: JSON.stringify({
            content: Buffer.from(readme).toString('base64'),
            encoding: 'base64',
          }),
        },
        githubToken
      );
      treeItems.push({ path: 'README.md', mode: '100644', type: 'blob', sha: blob.sha });
    }

    // Create tree → commit → update ref
    const newTree = await ghRequest<{ sha: string }>(
      `/repos/${owner}/${repoName}/git/trees`,
      {
        method: 'POST',
        body: JSON.stringify({ base_tree: baseTreeSha, tree: treeItems }),
      },
      githubToken
    );

    const newCommit = await ghRequest<{ sha: string; html_url: string }>(
      `/repos/${owner}/${repoName}/git/commits`,
      {
        method: 'POST',
        body: JSON.stringify({
          message: commitMessage,
          tree: newTree.sha,
          parents: [latestCommitSha],
        }),
      },
      githubToken
    );

    await ghRequest<unknown>(
      `/repos/${owner}/${repoName}/git/refs/heads/${branch}`,
      {
        method: 'PATCH',
        body: JSON.stringify({ sha: newCommit.sha, force: false }),
      },
      githubToken
    );

    const repoUrl = repo.html_url;

    // Persist repo URL on project
    await client
      .from('projects')
      .update({ github_repo: `${owner}/${repoName}` })
      .eq('id', projectId);

    // Record deployment
    const { data: deploymentRow } = await client
      .from('project_deployments')
      .insert({
        project_id: projectId,
        provider: 'github',
        github_repo: `${owner}/${repoName}`,
        github_branch: branch,
        commit_sha: newCommit.sha,
        status: 'success',
        deployed_at: new Date().toISOString(),
      })
      .select('id')
      .single();

    return NextResponse.json({
      success: true,
      repoUrl,
      commitSha: newCommit.sha,
      commitUrl: newCommit.html_url,
      deploymentId: (deploymentRow as { id: string } | null)?.id,
    });
  } catch (err) {
    console.error('[publish/github]', err);
    const message = err instanceof Error ? err.message : 'GitHub publish failed';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
