/**
 * POST /api/projects/[id]/publish/github
 *
 * Pushes all current project_files to a GitHub repository using a PAT.
 *
 * Auth: Bearer token required. Caller must own the project.
 *
 * Body (JSON):
 *   {
 *     pat: string;            // GitHub Personal Access Token — never logged
 *     repoFullName?: string;  // "owner/repo" — required unless createRepo=true
 *     createRepo?: boolean;   // create a new repo first
 *     private?: boolean;      // repo visibility when creating (default false)
 *     branch?: string;        // target branch (default "main")
 *   }
 *
 * Returns: { repoUrl, branch, commitSha }
 */

import { NextResponse } from "next/server";
import {
  extractBearerToken,
  getUserFromToken,
  getProjectById,
  getProjectFiles,
  upsertDeploySettings,
} from "@/lib/db/projects-db";

export const runtime = "nodejs";

interface RouteParams {
  params: Promise<{ id: string }>;
}

interface GithubPublishBody {
  pat: string;
  repoFullName?: string;
  createRepo?: boolean;
  private?: boolean;
  branch?: string;
}

// ─── GitHub REST helpers ────────────────────────────────────────────────────

const GH_API = "https://api.github.com";

async function ghFetch(
  pat: string,
  path: string,
  options: RequestInit = {}
): Promise<Response> {
  const res = await fetch(`${GH_API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${pat}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...(options.headers ?? {}),
    },
  });
  return res;
}

async function ghJson<T>(
  pat: string,
  path: string,
  options: RequestInit = {}
): Promise<T> {
  const res = await ghFetch(pat, path, options);
  const json = await res.json() as T & { message?: string };
  if (!res.ok) {
    throw new Error(
      `GitHub API ${options.method ?? "GET"} ${path} → ${res.status}: ${
        (json as { message?: string }).message ?? JSON.stringify(json)
      }`
    );
  }
  return json as T;
}

// ─── Route handler ──────────────────────────────────────────────────────────

export async function POST(req: Request, { params }: RouteParams) {
  const { id: projectId } = await params;

  // ── Auth ───────────────────────────────────────────────────────────────────
  const token = extractBearerToken(req.headers.get("Authorization"));
  if (!token) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const user = await getUserFromToken(token);
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // ── Ownership check ────────────────────────────────────────────────────────
  const project = await getProjectById(token, projectId);
  if (!project) {
    return NextResponse.json({ error: "Project not found" }, { status: 404 });
  }
  if (project.owner_user_id !== user.id) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  // ── Parse body ─────────────────────────────────────────────────────────────
  let body: GithubPublishBody;
  try {
    body = (await req.json()) as GithubPublishBody;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { pat, createRepo = false, branch = "main" } = body;
  if (!pat || typeof pat !== "string") {
    return NextResponse.json({ error: "Missing required field: pat" }, { status: 422 });
  }

  let repoFullName = body.repoFullName ?? "";

  // ── Optionally create repo ─────────────────────────────────────────────────
  if (createRepo) {
    const repoName = project.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "zivo-project";

    try {
      const created = await ghJson<{ full_name: string }>(pat, "/user/repos", {
        method: "POST",
        body: JSON.stringify({
          name: repoName,
          private: body.private ?? false,
          auto_init: false,
          description: `Generated by ZIVO-AI – ${project.title}`,
        }),
      });
      repoFullName = created.full_name;
    } catch (err: unknown) {
      const msg = (err as Error).message ?? String(err);
      // 422 = repo already exists; reuse it
      if (!msg.includes("422") && !msg.includes("name already exists")) {
        return NextResponse.json({ error: `Failed to create repo: ${msg}` }, { status: 502 });
      }
      // Derive the expected full_name from the authenticated user
      const me = await ghJson<{ login: string }>(pat, "/user");
      repoFullName = `${me.login}/${repoName}`;
    }
  }

  if (!repoFullName) {
    return NextResponse.json(
      { error: "Missing required field: repoFullName (or set createRepo=true)" },
      { status: 422 }
    );
  }

  // ── Load project files ─────────────────────────────────────────────────────
  const files = await getProjectFiles(token, projectId);
  if (files.length === 0) {
    return NextResponse.json({ error: "No files to push" }, { status: 422 });
  }

  // ── Push to GitHub via Trees API ───────────────────────────────────────────
  // We use the low-level blobs → tree → commit → update-ref flow which works
  // regardless of whether the repo is empty or already has commits.

  try {
    // 1. Get or create base commit SHA (needed for the parent commit)
    let baseSha: string | null = null;
    let baseTreeSha: string | null = null;

    try {
      const ref = await ghJson<{ object: { sha: string } }>(
        pat,
        `/repos/${repoFullName}/git/refs/heads/${branch}`
      );
      baseSha = ref.object.sha;

      const commit = await ghJson<{ tree: { sha: string } }>(
        pat,
        `/repos/${repoFullName}/git/commits/${baseSha}`
      );
      baseTreeSha = commit.tree.sha;
    } catch {
      // Branch / repo doesn't exist yet — we'll create the first commit below
    }

    // 2. Create blobs for each file
    const treeItems: Array<{
      path: string;
      mode: string;
      type: string;
      sha: string;
    }> = [];

    for (const file of files) {
      const normalised = file.path.replace(/^\/+/, "");
      const blob = await ghJson<{ sha: string }>(
        pat,
        `/repos/${repoFullName}/git/blobs`,
        {
          method: "POST",
          body: JSON.stringify({
            content: Buffer.from(file.content).toString("base64"),
            encoding: "base64",
          }),
        }
      );
      treeItems.push({
        path: normalised,
        mode: "100644",
        type: "blob",
        sha: blob.sha,
      });
    }

    // 3. Create a new tree
    const treePayload: Record<string, unknown> = { tree: treeItems };
    if (baseTreeSha) treePayload.base_tree = baseTreeSha;

    const newTree = await ghJson<{ sha: string }>(
      pat,
      `/repos/${repoFullName}/git/trees`,
      {
        method: "POST",
        body: JSON.stringify(treePayload),
      }
    );

    // 4. Create commit
    const commitPayload: Record<string, unknown> = {
      message: `Deploy via ZIVO-AI – ${new Date().toISOString()}`,
      tree: newTree.sha,
    };
    if (baseSha) commitPayload.parents = [baseSha];

    const newCommit = await ghJson<{ sha: string; html_url: string }>(
      pat,
      `/repos/${repoFullName}/git/commits`,
      {
        method: "POST",
        body: JSON.stringify(commitPayload),
      }
    );

    // 5. Update (or create) the branch ref
    const refPath = `/repos/${repoFullName}/git/refs/heads/${branch}`;
    const updateRes = await ghFetch(pat, refPath, {
      method: "PATCH",
      body: JSON.stringify({ sha: newCommit.sha, force: true }),
    });

    if (!updateRes.ok && updateRes.status === 422) {
      // Ref doesn't exist yet — create it
      await ghJson(pat, `/repos/${repoFullName}/git/refs`, {
        method: "POST",
        body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: newCommit.sha }),
      });
    } else if (!updateRes.ok) {
      const errBody = await updateRes.json() as { message?: string };
      throw new Error(`Failed to update ref: ${errBody.message ?? updateRes.status}`);
    }

    const repoUrl = `https://github.com/${repoFullName}`;
    const commitSha = newCommit.sha;

    // 6. Persist deploy settings
    await upsertDeploySettings(token, projectId, {
      deploy_repo_url: repoUrl,
      deploy_branch: branch,
      last_pushed_commit_sha: commitSha,
      last_pushed_at: new Date().toISOString(),
    });

    return NextResponse.json({ repoUrl, branch, commitSha });
  } catch (err: unknown) {
    const msg = (err as Error).message ?? String(err);
    // Classify common errors
    if (msg.includes("401") || msg.includes("Bad credentials")) {
      return NextResponse.json({ error: "Invalid or expired PAT" }, { status: 401 });
    }
    if (msg.includes("403") || msg.includes("forbidden")) {
      return NextResponse.json({ error: "PAT lacks required permissions" }, { status: 403 });
    }
    if (msg.includes("404") || msg.includes("Not Found")) {
      return NextResponse.json({ error: "Repository not found" }, { status: 404 });
    }
    return NextResponse.json({ error: `GitHub push failed: ${msg}` }, { status: 502 });
  }
}
