// POST { appName?, primaryColor?, style?, fontFamily? }
// Returns { files, designTokens, summary }
import { NextResponse } from "next/server";
import { generateDesignSystem } from "@/lib/design/design-system";
import { DesignSystemRequestSchema } from "@/lib/schemas";

export const runtime = "nodejs";

type StyleOption = "minimal" | "modern" | "bold";
const VALID_STYLES: StyleOption[] = ["minimal", "modern", "bold"];

export interface DesignTokenOutput {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  text: string;
  radius: string;
  fontFamily: string;
}

export interface DesignSystemFile {
  path: string;
  content: string;
  action: "create";
}

export interface DesignSystemResponse {
  files: DesignSystemFile[];
  designTokens: DesignTokenOutput;
  summary: string;
}

export async function POST(req: Request): Promise<Response> {
  try {
    const body = await req.json().catch(() => ({})) as {
      appName?: string;
      primaryColor?: string;
      style?: string;
      fontFamily?: string;
      // Legacy fields kept for backward compatibility
      description?: string;
      mood?: string;
    };

    const schemaResult = DesignSystemRequestSchema.safeParse(body);
    if (!schemaResult.success) {
      return NextResponse.json({ error: schemaResult.error.issues }, { status: 400 });
    }

    const {
      appName = "My App",
      primaryColor = "#6366f1",
      style,
      fontFamily = "Inter",
      description,
      mood,
    } = body;

    const validStyle: StyleOption = VALID_STYLES.includes(style as StyleOption)
      ? (style as StyleOption)
      : "modern";

    // Build description for the generator
    const effectiveDescription = description || `${appName} — ${validStyle} design system with ${primaryColor} as primary color`;

    type Mood = "modern" | "playful" | "minimal" | "bold" | "elegant";
    const MOOD_MAP: Record<StyleOption, Mood> = { bold: "bold", minimal: "minimal", modern: "modern" };
    const effectiveMood: Mood = (mood as Mood) ?? MOOD_MAP[validStyle];

    const system = await generateDesignSystem(effectiveDescription, effectiveMood);

    const primary = (system.tokens?.colors?.primary as string | undefined) ?? primaryColor;
    const secondary = (system.tokens?.colors?.secondary as string | undefined) ?? "#3f3f46";
    const accent = (system.tokens?.colors?.accent as string | undefined) ?? "#818cf8";
    const background = (system.tokens?.colors?.background as string | undefined) ?? "#09090b";
    const text = (system.tokens?.colors?.foreground as string | undefined) ?? "#fafafa";
    const radius = (system.tokens?.borderRadius?.DEFAULT as string | undefined) ?? "0.5rem";

    const designTokens: DesignTokenOutput = {
      primary,
      secondary,
      accent,
      background,
      text,
      radius,
      fontFamily,
    };

    // Generate the files for the design system
    const tailwindContent = `import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: { DEFAULT: "${primary}", foreground: "#ffffff" },
        secondary: { DEFAULT: "${secondary}", foreground: "#fafafa" },
        accent: { DEFAULT: "${accent}", foreground: "#ffffff" },
        background: "${background}",
        foreground: "${text}",
      },
      fontFamily: {
        sans: ["${fontFamily}", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "${radius}",
        sm: "calc(${radius} - 2px)",
        md: "${radius}",
        lg: "calc(${radius} + 2px)",
        xl: "calc(${radius} + 4px)",
      },
    },
  },
  plugins: [],
};

export default config;
`;

    const globalsContent = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --primary: ${primary};
  --secondary: ${secondary};
  --accent: ${accent};
  --background: ${background};
  --foreground: ${text};
  --radius: ${radius};
  --font-sans: "${fontFamily}", system-ui, sans-serif;
}

@layer base {
  * { box-sizing: border-box; }
  body {
    background-color: var(--background);
    color: var(--foreground);
    font-family: var(--font-sans);
  }
}
`;

    const tokensContent = `// Design tokens for ${appName}
// Auto-generated by ZIVO AI Design System

export const tokens = {
  colors: {
    primary: "${primary}",
    secondary: "${secondary}",
    accent: "${accent}",
    background: "${background}",
    text: "${text}",
  },
  fontFamily: "${fontFamily}",
  borderRadius: "${radius}",
} as const;

export type DesignTokens = typeof tokens;
`;

    const files: DesignSystemFile[] = [
      { path: "tailwind.config.ts", content: tailwindContent, action: "create" },
      { path: "app/globals.css", content: globalsContent, action: "create" },
      { path: "components/ui/tokens.ts", content: tokensContent, action: "create" },
    ];

    const response: DesignSystemResponse = {
      files,
      designTokens,
      summary: system.name
        ? `Generated design system "${system.name}" with ${validStyle} style and ${primary} primary color.`
        : `Generated ${validStyle} design system for ${appName}.`,
    };

    return NextResponse.json(response);
  } catch (err: unknown) {
    return NextResponse.json({ error: (err as Error)?.message ?? "Server error" }, { status: 500 });
  }
}
