import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { extractBearerToken, getUserFromToken, createAuthedClient } from '@/lib/db/projects-db';

export const runtime = 'nodejs';

const RequestSchema = z.object({
  projectId: z.string().uuid(),
  repoName: z.string().min(1).max(100).regex(/^[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9]$|^[a-zA-Z0-9]$/, 'Invalid repo name'),
  isPrivate: z.boolean().optional().default(true),
  commitMessage: z.string().optional().default('feat: publish from ZIVO-AI'),
  githubToken: z.string().min(1),
});

const GITHUB_API = 'https://api.github.com';

interface GithubRepoResponse {
  full_name: string;
  html_url: string;
  default_branch: string;
}

interface GithubFileResponse {
  sha?: string;
}

interface GithubCommitResponse {
  sha: string;
  html_url: string;
}

async function githubRequest<T>(
  path: string,
  options: RequestInit,
  githubToken: string
): Promise<T> {
  const res = await fetch(`${GITHUB_API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${githubToken}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
      ...(options.headers ?? {}),
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`GitHub API ${path} → ${res.status}: ${body}`);
  }
  return res.json() as Promise<T>;
}

export async function POST(req: NextRequest) {
  try {
    // Auth check
    const token = extractBearerToken(req.headers.get('authorization'));
    if (!token) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const user = await getUserFromToken(token);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const parsed = RequestSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: 'Invalid request', details: parsed.error.flatten() }, { status: 400 });
    }
    const { projectId, repoName, isPrivate, commitMessage, githubToken } = parsed.data;

    // Fetch project files from Supabase
    const supabase = createAuthedClient(token);
    const { data: project, error: projectError } = await supabase
      .from('projects')
      .select('id, title')
      .eq('id', projectId)
      .eq('owner_user_id', user.id)
      .single();

    if (projectError || !project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    const { data: files } = await supabase
      .from('project_files')
      .select('path, content')
      .eq('project_id', projectId);

    // Get GitHub username
    const ghUser = await githubRequest<{ login: string }>('/user', { method: 'GET' }, githubToken);
    const owner = ghUser.login;

    // Create repo if it doesn't exist, otherwise get existing
    let repo: GithubRepoResponse;
    try {
      repo = await githubRequest<GithubRepoResponse>(
        `/repos/${owner}/${repoName}`,
        { method: 'GET' },
        githubToken
      );
    } catch {
      repo = await githubRequest<GithubRepoResponse>(
        '/user/repos',
        {
          method: 'POST',
          body: JSON.stringify({
            name: repoName,
            description: `Generated by ZIVO-AI: ${project.title}`,
            private: isPrivate,
            auto_init: true,
          }),
        },
        githubToken
      );
    }

    const branch = repo.default_branch || 'main';

    // Get latest commit SHA for the branch
    const refData = await githubRequest<{ object: { sha: string } }>(
      `/repos/${owner}/${repoName}/git/ref/heads/${branch}`,
      { method: 'GET' },
      githubToken
    );
    const latestCommitSha = refData.object.sha;

    // Get tree SHA
    const commitData = await githubRequest<{ tree: { sha: string } }>(
      `/repos/${owner}/${repoName}/git/commits/${latestCommitSha}`,
      { method: 'GET' },
      githubToken
    );
    const baseTreeSha = commitData.tree.sha;

    // Build tree from project files
    const filesToPush = files ?? [];
    const treeItems = await Promise.all(
      filesToPush.map(async (f: { path: string; content: string }) => {
        const blobRes = await githubRequest<{ sha: string }>(
          `/repos/${owner}/${repoName}/git/blobs`,
          {
            method: 'POST',
            body: JSON.stringify({
              content: Buffer.from(f.content).toString('base64'),
              encoding: 'base64',
            }),
          },
          githubToken
        );
        return { path: f.path, mode: '100644', type: 'blob', sha: blobRes.sha };
      })
    );

    // Add README if no files
    if (treeItems.length === 0) {
      const readme = `# ${project.title}\n\nGenerated by [ZIVO-AI](https://zivo.ai).\n`;
      const blobRes = await githubRequest<{ sha: string }>(
        `/repos/${owner}/${repoName}/git/blobs`,
        {
          method: 'POST',
          body: JSON.stringify({ content: Buffer.from(readme).toString('base64'), encoding: 'base64' }),
        },
        githubToken
      );
      treeItems.push({ path: 'README.md', mode: '100644', type: 'blob', sha: blobRes.sha });
    }

    // Create new tree
    const newTree = await githubRequest<{ sha: string }>(
      `/repos/${owner}/${repoName}/git/trees`,
      {
        method: 'POST',
        body: JSON.stringify({ base_tree: baseTreeSha, tree: treeItems }),
      },
      githubToken
    );

    // Create commit
    const newCommit = await githubRequest<GithubCommitResponse>(
      `/repos/${owner}/${repoName}/git/commits`,
      {
        method: 'POST',
        body: JSON.stringify({
          message: commitMessage,
          tree: newTree.sha,
          parents: [latestCommitSha],
        }),
      },
      githubToken
    );

    // Update branch ref
    await githubRequest<GithubFileResponse>(
      `/repos/${owner}/${repoName}/git/refs/heads/${branch}`,
      {
        method: 'PATCH',
        body: JSON.stringify({ sha: newCommit.sha, force: false }),
      },
      githubToken
    );

    const repoUrl = repo.html_url;

    // Update project record with GitHub repo
    await supabase
      .from('projects')
      .update({ github_repo: `${owner}/${repoName}` })
      .eq('id', projectId);

    return NextResponse.json(
      { repoUrl, commitSha: newCommit.sha, commitUrl: newCommit.html_url },
      { status: 200 }
    );
  } catch (err) {
    console.error('[publish-github]', err);
    const message = err instanceof Error ? err.message : 'Internal server error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
