import { NextResponse } from "next/server";

export const runtime = "nodejs";

const mockPlugins = [
  {
    id: "plugin-001",
    name: "SEO Optimizer",
    description: "Automatically optimizes your generated sites for search engines.",
    version: "1.2.0",
    author: "ZIVO Labs",
    downloads: 12400,
    rating: 4.8,
    category: "SEO",
    price: 0,
    installed: false,
  },
  {
    id: "plugin-002",
    name: "Dark Mode Generator",
    description: "Adds dark mode support to any generated website.",
    version: "2.0.1",
    author: "UIKit Dev",
    downloads: 8900,
    rating: 4.6,
    category: "UI",
    price: 0,
    installed: false,
  },
  {
    id: "plugin-003",
    name: "Analytics Injector",
    description: "Injects Google Analytics and custom tracking into generated pages.",
    version: "1.0.5",
    author: "TrackPro",
    downloads: 5600,
    rating: 4.4,
    category: "Analytics",
    price: 9.99,
    installed: false,
  },
  {
    id: "plugin-004",
    name: "Auth Scaffold",
    description: "Generates full authentication flows including login, register, and OAuth.",
    version: "3.1.0",
    author: "SecureStack",
    downloads: 21000,
    rating: 4.9,
    category: "Authentication",
    price: 19.99,
    installed: true,
  },
  {
    id: "plugin-005",
    name: "CMS Connector",
    description: "Connects generated sites to headless CMS platforms like Contentful and Sanity.",
    version: "1.4.2",
    author: "CMS Bridge",
    downloads: 7300,
    rating: 4.3,
    category: "CMS",
    price: 14.99,
    installed: false,
  },
  {
    id: "plugin-006",
    name: "Payment Gateway",
    description: "Adds Stripe and PayPal payment integration to e-commerce sites.",
    version: "2.2.0",
    author: "PayKit",
    downloads: 15800,
    rating: 4.7,
    category: "E-commerce",
    price: 24.99,
    installed: false,
  },
  {
    id: "plugin-007",
    name: "i18n Translator",
    description: "Auto-translates your site into 50+ languages using AI.",
    version: "1.1.3",
    author: "LangFlow",
    downloads: 4200,
    rating: 4.2,
    category: "Localization",
    price: 0,
    installed: false,
  },
  {
    id: "plugin-008",
    name: "Performance Booster",
    description: "Optimizes images, code splitting, and lazy loading automatically.",
    version: "1.0.0",
    author: "SpeedKit",
    downloads: 9100,
    rating: 4.5,
    category: "Performance",
    price: 0,
    installed: false,
  },
];

export async function GET() {
  return NextResponse.json({ plugins: mockPlugins });
}
